### ISSUE TITLE
Forum Replies have blank post_title field in the wp_posts database table

### ISSUE THREAD

**Issue by kishanjasani** [buddyboss/buddyboss-platform#2956] opened 2021-09-20 10:03 UTC
**Describe the bug**
when you create a reply in the forum, they get saved in the database with a blank post_title field. Yet, when you move, split, merge, etc... they receive a title of "Reply To: [topic title]". So, there is no problem with having a title and this is just an oversight.

Moreover, he notice that there is a function (which doesn't seem to get used anywhere in the code) called bbp_get_reply_title_fallback, which exists to specifically apply this title to an empty reply title.

Noticed it previously, but only addressed it now when this caused a major conflict with a search plugin when it tries to index the new reply.

**To Reproduce**
1. Go to 'Any forum'
2. Create reply
3. See error

**Support ticket links**
https://secure.helpscout.net/conversation/1620786761/162231/

**Comment by nickchomey** [comment] 2021-11-18 08:14
You can probably close this issue as it is a duplicate of https://github.com/buddyboss/buddyboss-platform/issues/2878

**Closed** 2021-11-18 10:53 UTC
Labels: bug, status: need discussion
