### ISSUE TITLE
Rest api create reply , edit reply document upload not work and not showing in replies api properly

### ISSUE THREAD

**Issue by bhavik-s-eq** [buddyboss/buddyboss-platform#1591] opened 2020-10-05 11:35 UTC
After update latest version 1.5 still have issue . Please resolve asap

**Comment by mahedihasannoman** [comment] 2021-09-14 13:35
Hi @bhavik-s-eq , We are not able to reproduce this issue. Can you please confirm if you are able to then share the steps to re-produce this issue. Otherwise please close this ticket.

**Closed** 2021-09-15 04:02 UTC
Labels: bug, bug: can't reproduce, priority: medium
