### ISSUE TITLE
Feed photos flash before uploading to Mobile

### ISSUE THREAD

**Issue by Felipemauah** [buddyboss/buddyboss-platform#2579] opened 2021-07-07 00:08 UTC
**Describe the bug**
When I open the Feed and start scrolling through it, whenever there is an image posted in Feed or in Groups, these images show a Flash before loading. Images uploaded to Jobs or Resumes that appear in Feed do not have this issue.

**To Reproduce**

1 Make varied posts with images
2 Update Feed
3 Browse Feed normally

**Expected behavior**
Charge before to apear in window 

**Video Proof**
https://youtu.be/XYNZdH3gFyc

**Comment by mahedihasannoman** [comment] 2021-09-06 11:23
Hi @Felipemauah , As per checking this is not a bug. We are loading the the images only when they are in viewport in order to reduce the over all loading time and best user experience. So please close this ticket.

**Closed** 2021-09-07 09:59 UTC
Labels: bug, bug: needs validating
