### ISSUE TITLE
Not all the search result items for the lesson are being shown

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#589] opened 2020-02-21 19:07 UTC
**Describe the bug**
When you search a lesson on the frontend, the search result counter is correct but the search result items are incomplete or do not match with the search result counter.

**To Reproduce**
1. Create at least 15 lessons with related keywords
2. Search on the frontend and you can notice that not all the items are being shown

**Expected behavior**
All the search items should appear

**Screenshots**

-  On the backend, there are 12 results for the keyword "abc"
![lesson](https://user-images.githubusercontent.com/58522498/75063478-fe7a5a80-551f-11ea-9563-47d5a4cc9720.png)

-  On the frontend, it is indicated that there are 12 results found for the lesson but only 10 items are listed
![lesson-result](https://user-images.githubusercontent.com/58522498/75063598-397c8e00-5520-11ea-8a25-b554853ab6bd.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1111927002/1827/

**Comment by Anve-sri** [comment] 2020-02-27 07:37
Received https://buddyboss.zendesk.com/agent/tickets/62960 ticket for a similar issue with Woocommerce products. 
![inline-1060840729](https://user-images.githubusercontent.com/58801078/75422256-26bfea00-5962-11ea-8793-adccfc998039.png)

**Comment by janakkaneriya007** [comment] 2020-04-14 08:16
Possible duplicate of: https://github.com/buddyboss/buddyboss-platform/issues/701

**Comment by janakkaneriya007** [comment] 2020-05-05 08:41
This issue is fixed here: https://github.com/buddyboss/buddyboss-platform/issues/701

**Closed by janakkaneriya007** 2020-05-05 08:41 UTC
Labels: Status: Duplicate, bug, component: search, duplicate, priority: high
