### ISSUE TITLE
Activity date translation in activity feed not working on Translatepress

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1216] opened 2020-07-16 16:52 UTC
**Describe the bug**
When using the Translatepress plugin, the Activity date is not being translate, regardless of the date, it still says "right now"

**To Reproduce**
1. Install Translatepress
2. Setup/Add a different language in Settings > Translatepress > General > All languages 
3. Go to Activity feed
4. Change to a different language
5. See error

**Expected behavior**
Date should also be Translated

**Screenshots**
https://drive.google.com/file/d/13EFuArUSoCa6e2jBhunfTJy59VVpO3Lt/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1225325557/83293

**Comment by sumitbuddyboss** [comment] 2020-07-29 15:41
@shohel 

**Issue**
When user use Google translate ([Default Google Chrome translate](https://prnt.sc/tqm5uu) ) at that time the spacing getting  removed between the word. Please check video below.

**Video:**
https://www.loom.com/share/1d3a860d92cd440989627a4f2ca8527d


CC @ankitguptaindia

**Comment by chetansatasiya** [comment] 2020-08-19 09:39
Duplicate of https://github.com/buddyboss/buddyboss-platform/issues/1155

**Closed by chetansatasiya** 2020-08-19 09:39 UTC
Labels: Has-PR, bug, component: activity, priority: medium, translation
