### ISSUE TITLE
Pagination on the user profile page for "My Discussions" and "My Replies" throws 404 error. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#734] opened 2020-04-12 07:02 UTC
**Describe the bug**
Pagination on the user profile page for "My Discussions" and "My Replies" throws 404 error. Tested this using the latest version of the plugin on my local. I could replicate this on our demo site too. 

**To Reproduce**
1. Go to User Profile > My Discussions / My Replies page
2. Click on Arrow or number to change the page
3. See error

**Expected behavior**
The pagination should work fine without issue. 

**Screenshots**
- https://cl.ly/b9b5e211e3af

**Support ticket links**
- https://secure.helpscout.net/conversation/1132272582/67769/

**Comment by janakkaneriya007** [comment] 2020-04-13 05:31
Hi @archanabb 

Possibly duplicate of: https://github.com/buddyboss/buddyboss-platform/issues/696

**Comment by janakkaneriya007** [comment] 2020-05-05 08:39
This issue is fixed here: https://github.com/buddyboss/buddyboss-platform/issues/696

**Closed by janakkaneriya007** 2020-05-05 08:40 UTC
Labels: bug, component: profiles, duplicate, priority: medium
