### ISSUE TITLE
Fatal Error if BP is active

### ISSUE THREAD

**Issue by ankitguptaindia** [buddyboss/buddyboss-platform#340] opened 2019-12-11 11:04 UTC
**Bug-**  If site has BP activated and we activated Platform then Site get down and giving Fatal error.

**How to reproduce-** 
https://www.loom.com/share/5bcf2602f2ef443186718947c10f22dd

**Comment by chetansatasiya** [comment] 2020-03-17 11:47
@ankitguptaindia I am not able to reproduce this issue now. Can you check again and let me know if the issue still coming?

**Comment by ankitguptaindia** [comment] 2020-03-26 08:31
@chetansatasiya I am using Latest Dev of Platfrom and Theme. I can see still the issue.
Rfer- https://www.loom.com/share/4d05e59486f24cce9eb982455be3eb6b

First Activate BP then activate BuddyBoss Platform.

**Comment by mohit-buddyboss** [comment] 2021-02-08 05:33
@chetansatasiya  As per sourabh we will not work on making BB product compatible with BP. So, closing this issue.

**Closed** 2021-02-08 05:34 UTC
Labels: bug, priority: high
