### ISSUE TITLE
The Events Calendar > Activity post doesn't show the video preview

### ISSUE THREAD

**Issue by surajkrsingh** [buddyboss/buddyboss-platform#2937] opened 2021-09-15 11:43 UTC
**Describe the bug**
Creating an event and adding content with a video URL doesn't show the video preview on the activity post.
After debugging we found the issue is from Buddyboss platform v1.7.2 whereas it working fine with BB Platform v1.7.1 or older

We compared and found many changes regarding the activity CPT post - https://github.com/buddyboss/buddyboss-platform/compare/1.7.1...1.7.2

**To Reproduce**
1. Installed the event calendar plugin
2.  Activate the event CPT from activity settings
3. Create a new event and add the content and video URL with it
4. Publish the event
5. Check the activity feed post

**Expected behavior**
The video should have a preview with contents - 
https://tinyurl.com/yzemplzs (with version 1.7.1)

**Screenshots**
https://tinyurl.com/yjyunvxa (with version 1.7.6)

**Environment**
Buddyboss Demo site
Dev local site 
Customer site

**Support ticket links**
https://secure.helpscout.net/conversation/1575129859/154142?folderId=3709082

**Comment by bb-yudhisthir** [comment] 2021-10-01 05:47
@surajkrsingh confirmed with @asaquzzamanbb  its the default behaviour with the 1.7.2 release as we are showing the excerpt of posts in the activity feed and the full content will show in their respective single page via view post/read more link

**Comment by sourabhmatolia** [comment] 2021-10-01 10:20
**Further clarity here**

We cannot work on this because of the kind of layout we planned to present in the auto-generated activity feed for the blog posts.
IF try to show post content then we don’t have control over what to show and how to show.
Post content consists of Gutenberg blocks, scripts, HTML, embeds, and whatnot. That too in a different order, different layout, different markup. N number of possibilities on how to post content can be added.
So we decided to strip all that and show plain text excerpt.
That’s a universal solution that might work best for all.
Thanks

**Comment by bb-yudhisthir** [comment] 2021-10-01 11:24
@surajkrsingh closing this issue

**Closed by bb-yudhisthir** 2021-10-01 11:24 UTC
Labels: bug, bug: needs validating
