### ISSUE TITLE
Notice and Warning on Group Single page - Notice: Trying to access array offset on value of type int in 

### ISSUE THREAD

**Issue by ankitguptaindia** [buddyboss/buddyboss-platform#903] opened 2020-05-14 15:02 UTC
**Describe the bug**
There are some Notices on Group Single page when Debug Mode ON

```
Notice: Trying to access array offset on value of type int in /Users/ank/Local Sites/apitesting/app/public/wp-includes/formatting.php on line 904
Warning: Cannot modify header information - headers already sent by (output started at /Users/ank/Local Sites/apitesting/app/public/wp-includes/formatting.php:904) in /Users/ank/Local Sites/apitesting/app/public/wp-includes/pluggable.php on line 1281
Warning: Cannot modify header information - headers already sent by (output started at /Users/ank/Local Sites/apitesting/app/public/wp-includes/formatting.php:904) in /Users/ank/Local Sites/apitesting/app/public/wp-includes/pluggable.php on line 1284

```

**Expected behavior**
No error/warning should appear on page. Log should be clear.

**Screenshots**
https://i.imgur.com/CsCfnE0.jpg

**Support ticket links**
N/A -  reported by QA

**Comment by eisenwasser** [comment] 2020-05-30 18:19
@KartikSuthar Simple issue, could use your help

**Comment by KartikSuthar** [comment] 2020-07-20 05:53
@ankitguptaindia I have checked with the dev branch of theme and platform and can not reproduce the issue.
Can you please check and inform me of the steps to reproduce.

**Comment by chetansatasiya** [comment] 2020-08-05 06:29
This is fixed in recent release so I am closing now as this can't reproduce.

**Closed by chetansatasiya** 2020-08-05 06:29 UTC
Labels: bug, can't reproduce, priority: medium
