### ISSUE TITLE
Search results hides if you scroll the page on an iOS device.

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#926] opened 2020-05-22 08:15 UTC
**Describe the bug**
Search results hides if you scroll the page on an iOS device.

**To Reproduce**
1. Open the site on iphone. 
2. Type something in search
3. Scroll 
4. Search result hides

**Screenshots**
[vid.zip](https://github.com/buddyboss/buddyboss-platform/files/4666862/vid.zip)

**Support ticket links**
https://secure.helpscout.net/conversation/1170534447/74308?folderId=3701249

**Comment by imehedidev** [comment] 2021-09-14 10:39
Duplicate of #795

**Closed by imehedidev** 2021-09-14 10:39 UTC
Labels: bug, priority: medium
