### ISSUE TITLE
Some pages do not work when private network is enabled and WooCommerce plugin is active: User Specific issue

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#1321] opened 2020-08-07 14:02 UTC
**Describe the bug**
Some pages do not work when a private network is enabled and WooCommerce plugin is active.

**To Reproduce**
1. Go to BuddyBoss settings and enable private network
2. visit member's profile page on the front end without logging in to the site
3. See error

**Expected behavior**
The pages should not be accessible when the private network is enabled. 

**Screenshots**
-

**Support ticket links**
- https://secure.helpscout.net/conversation/1224116984/83124?folderId=3701247

**Comment by chetansatasiya** [comment] 2020-08-28 04:22
@shohel @shohelbuddyboss We need the specific steps to reproduce this as this is working fine with `dev` branch.

**Comment by chetansatasiya** [comment] 2020-08-28 04:26
CC @sourabhmatolia

**Comment by sumitbuddyboss** [comment] 2020-09-01 07:05
Hello @chetansatasiya 

Tested in the dev branch and can't reproduce the issue, Please check the below video.

**Video:**
https://www.loom.com/share/12434bc286a64984a455650e1aa1a500


CC @ankitguptaindia

**Comment by chetansatasiya** [comment] 2021-01-05 08:59
Closing this as this is not reproducable anymore.

**Closed by chetansatasiya** 2021-01-05 08:59 UTC
Labels: Type: Support, can't reproduce, priority: medium
