### ISSUE TITLE
Private messaging to a user keeps adding some random users to the chat. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#860] opened 2020-05-07 09:27 UTC
**Describe the bug**
Private messaging to a user keeps adding some random users to the chat. This has something to do with the connection option "Require users to be connected before they can message each other". 

I have received three tickets for this issue and all the users said that they had this option disabled first and then enabled it lately. That is causing the issue. 

**To Reproduce**
1. Go to Profile > Messages
2. Compose a personal message to one of your connections
3. See error

**Expected behavior**
Private messaging should not add some random users to the chat. 

**Screenshots**
- https://prnt.sc/s2hpdo

**Support ticket links**
- https://secure.helpscout.net/conversation/1154852884/71818/
- https://secure.helpscout.net/conversation/1135218417/68405/
- https://secure.helpscout.net/conversation/1157649807/72283/

**Comment by KartikSuthar** [comment] 2020-06-04 10:52
@archanabb , I have checked with the issue, and it's related to the client sites DB.
I have fixed the issue for the above 2 support tickets.

Also, I have tried to reproduce in my local but I can't reproduce.

@ankitguptaindia , Can you please check this issue at your end? Please let me know if you can reproduce.

**Comment by KartikSuthar** [comment] 2020-06-11 14:21
@archanabb Fixed on the client site.

**Comment by chetansatasiya** [comment] 2020-08-05 06:31
We tested a lot and can't reproduce this issue and this issue is coming to 3 to 4 customers but we can't found the pattern. So at this moment closing this issue and also we fixed this issues to above listed customers via manually deleting the entry from the DB.

**Closed by chetansatasiya** 2020-08-05 06:31 UTC
Labels: bug, can't reproduce, component: messages, priority: critical
