### ISSUE TITLE
Mention not working properly on Mobile - Android 9

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1350] opened 2020-08-13 17:09 UTC
**Describe the bug**
On mobile, with Android v9. The @mention is not working on replying comments on Activity feed or posting directly on Activity feed

**To Reproduce**
Issue can be replicated on demo
1. Use an Android 9 phone
2. Go to Activity feed in demo
3. Reply to some comments by @mention someone and add text
   or @mention someone then click spacebar 

**Expected behavior**
The issue happens when using Android 9.
When tagging someone, after you click their name and hit spacebar, this eaither deletes the TAG or doubles the TAG
The behavior is randomly happening after tagging. On some devices, @mention text @mention the "2nd @mention" will not work also.
On Android 10, this is randomly happening, after tagging someone in @mention, this creates a spacebar automatically, but sometimes when you hit spacebar, this also deletes the tag

**Notes**
This issue is tested on our demo using actual device and Browserstack

**Screenshots**
Android 9 browserstack - https://drive.google.com/file/d/1u-trk3nxBWa4gXovzB0I_yPZvYrt4F3E/view?usp=sharing
Android 10 browserstack - https://drive.google.com/file/d/1dH_6zPM4PM3oc9UvqjpzTZKn65r1fCdK/view?usp=sharing
Actual Android 9 - 

**Support ticket links**
https://secure.helpscout.net/conversation/1237123523/85258

**Comment by dipskakadiya** [comment] 2020-09-16 11:08
@emmanoctaviano I tested on dev branch I can't reproduce it
I think it's resolved with https://github.com/buddyboss/buddyboss-platform/pull/1470

Proof : https://screencast-o-matic.com/watch/cYQDXiJyE0

**Closed by dipskakadiya** 2020-09-16 11:08 UTC
Labels: bug, component: activity, priority: high, priority: medium
