### ISSUE TITLE
Getting 503 Error Conflict With Events Manager Pro And Buddy Boss

### ISSUE THREAD

**Issue by mountainhuntr** [buddyboss/buddyboss-platform#2426] opened 2021-05-24 22:02 UTC
### 
**Hello Support,
We have a bug in our site in that when we setup Events Manager Pro to receive payments from PayPal, that we would get a 503 error when trying to view an event that has paid tickets setup for registration. The support team at EM Pro has dug into this issue and have told us that the conflict is coming from Buddy Boss. Here are the details of the ticket with EM Pro and their response. (Please let us know if you can help troubleshoot why Buddy Boss may be causing this conflict and what we can do to correct it. If we cannot receive payments upon registration with EM Pro because of Buddy Boss, that causes a serious problem for us.)** 

hello,
I just added PayPal to my site so I can gather payments for my events. after following your docs on the subject I created a test event to test and make sure everything is working. after setting up the event, I went to view my paid event but it timed out on me after about 1 min. I created a free event and it didn't give me any problem.
I don't know if this helps, but here what my error log has repeated since May 2 of this year 

[11-May-2021 17:10:56 UTC] PHP Warning:  Declaration of EM_Event_Locations\Zoom_Meeting::output($what = NULL) should be compatible with EM_Event_Locations\Event_Location::output($what = NULL, $target = NULL) in /home/cagnetwo/public_html/ontrackfg.com/wp-content/plugins/events-manager-zoom/event-locations/em-event-location-zoom-meeting.php on line 870

[11-May-2021 17:10:56 UTC] PHP Warning: Declaration of EM_Event_Locations\Zoom_Room::output($what = NULL) should be compatible with EM_Event_Locations\Event_Location::output($what = NULL, $target = NULL) in /home/cagnetwo/public_html/ontrackfg.com/wp-content/plugins/events-manager-zoom/event-locations/em-event-location-zoom-room.php on line 81
I contacted my web host's support and they said that it is possible that these variables might be causing the problem because the script is waiting for them to change and they are not. Also, they changed the timeout amount to as long as they can, but it doesn't fix the problem.
here is a link to a video showing the problem: https://ontrackfg.com/wp-content/uploads/2021/05/Untitled.m4v
Let me know what I can do for you
Thanks

**Their response:**
Hi,
It looks like it's a conflict with the BuddyBoss Platform plugin since we set up and enables WP Safe Mode and we are getting Error 503 every time we enable the BuddyBoss Platform plugin; you can check your PHP error log to see if there's an additional error that might cause this issue.

**Please let us know if there is anything else you need to help you troubleshoot **this** bug for us.**

**Comment by marienel21** [comment] 2021-08-17 11:58
Hi @mountainhuntr 

Thank you for adding this issue, however as per the [notes](https://github.com/buddyboss/buddyboss-platform#support), this repository is not suitable for support issues. I’m going to close this ticket but if the problem is still outstanding please submit a support request at your [BuddyBoss.com](https://www.buddyboss.com/) account.

Thanks,
Marienel - BuddyBoss Product Team

**Closed by marienel21** 2021-08-17 11:58 UTC
Labels: bug, priority: medium
