### ISSUE TITLE
Groups going to 404 when they don't have a Home tab

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#1891] opened 2020-12-13 07:02 UTC
Describe the bug:
Customer said: 
User who is visiting HAS NOT JOINED THE GROUP. If it has, if THE USER HAS JOINED THAT GROUP, then it doesn't work fine. 
Use View As to view the site as Ramon Leonato, that is enrolled in almost every group there is. And you will see how this happens in EVERY group that has no home tab defined using the plugin. And again, that was not happening a few days ago, and if as you say there's no plugin conflict, it is your responsability to fix it.

Look at this video, and do the same as what the video shows
https://youtu.be/HAE9bXddxkc
And then answer if that has something to do with the way groups are created. All the groups shown in the video worked fine before the latest update of your software.

**********************

We have verified your staging website and found that "BuddyPress Group Tabs Creator Pro" plugin is conflicting with your group link 404 error. After deactivated "BuddyPress Group Tabs Creator Pro" plugin, Group links are working fine.

Screenshots:
https://www.loom.com/share/ecf3071c0e1540cbbfd4747b1f1699f1

Customer Ticket no
https://secure.helpscout.net/conversation/1361434199/113833?folderId=4265312

**Comment by jitendrabanjara1991** [comment] 2021-01-06 15:41
Hello @shyamwp14 

I checked in local site with **BuddyPress Group Tabs Creator Pro** but didn't reproduce same issue in local which is displaying on customer staging site in the video. Customer using old plugin(1.5.4). So I have also tested with that version. I have also attached two video. You can check it what I have tested.
With Old plugins version 1.5.4 - https://screencast-o-matic.com/watch/crVhFvP2Bx
With latest plugins version 1.5.6 - https://screencast-o-matic.com/watch/crVhFeP2tL

**Comment by jitendrabanjara1991** [comment] 2021-01-14 05:01
As per discussion with @shyamwp14, the Issue is not replicable anymore with the latest plugin **BuddyBoss Platform(1.5.6)**. Everything seems to work fine. So, I am Closing the issue. Thanks.

**Closed by jitendrabanjara1991** 2021-01-14 05:01 UTC
