### ISSUE TITLE
Groups discussions - SERP title

### ISSUE THREAD

**Issue by Gabrymi93** [buddyboss/buddyboss-platform#2253] opened 2021-03-19 10:11 UTC
**Describe the bug**
Title group discussions take the name of the Group itself in SERPs results. A discussion, even if associated with a group should have its own templates, as well as in standalone forums.

**To Reproduce**
Just test a standalone discussion and a group discussion with a SERP simulator https://technicalseo.com/tools/google-serp-simulator/

**Expected behavior**
It would be better to have Discussion title for SEO purposes and correct indexing.

**Screenshots**
![group-discussion-serp](https://user-images.githubusercontent.com/78922322/111764287-57dbc700-88a3-11eb-9281-1dc92b42ac78.JPG)

**Support ticket links**
ticket ID #126634

**Comment by surajkrsingh** [comment] 2021-12-13 03:54
@Gabrymi93 
We tested the forums and discussion with the given tools and it get the correct title on the results.
Please check this - https://www.loom.com/share/a4df13e90b684dd6b1e6ce1cc76f01d8

Let me know if you have any questions otherwise, we will close this issue.

**Comment by Gabrymi93** [comment] 2021-12-13 09:44
Hi @surajkrsingh 
Thanks for checking this out.
The issue is with Group discussions. As far as I can see from your video, you checked it for standalone forums and discussions.
Please test a group discussion and you'll see it will take the group title instead of the discussion title.
Thanks

**Comment by surajkrsingh** [comment] 2021-12-14 03:29
@Gabrymi93 
We got your point on the group discussion.
SERP read the page title for the SEO result.

And the group discussion page title is the same which is shown in SEO.
![image](https://user-images.githubusercontent.com/19591301/145927775-a8cf059f-4185-4a42-90c8-9d31fb0279ee.png)

I am not sure, we can change the page title for that.
Let me discuss this issue with the senior and will back to you.

Thank you

**Comment by surajkrsingh** [comment] 2021-12-17 02:52
Hello @Gabrymi93 
We discussed your concern with the senior team.

This can be done with custom code.
If you use the Yoast plugin then there should be some filter( like wpseo_title) to update it.

**Comment by surajkrsingh** [comment] 2021-12-19 16:37
As per the recent reply, It is not a bug but a custom requirement.
And It doesn't require any fix on the product.
but you can do the custom code to meet your requirement.

I am closing this issue.

**Closed by surajkrsingh** 2021-12-19 16:37 UTC
Labels: bug, priority: medium
