### ISSUE TITLE
Upload photo and acquire.io chatbot

### ISSUE THREAD

**Issue by prototype23** [buddyboss/buddyboss-platform#2122] opened 2021-02-08 17:22 UTC
**Describe the bug**
On the Profile Photo upload page, when you select to upload a Profile Photo, it throws a JS error:

`Uncaught TypeError: this.views is undefined
    addFile https://www.customedialabs.com/experience/wp-content/plugins/buddyboss-platform/bp-core/js/bp-plupload.min.js?ver=1.5.6:1
    ae https://assets.acquire.io/dist/54.443e265a9035.bundle.min.js:31
    au https://assets.acquire.io/dist/54.443e265a9035.bundle.min.js:31
    initialize https://www.customedialabs.com/experience/wp-content/plugins/buddyboss-platform/bp-core/js/bp-plupload.min.js?ver=1.5.6:1
    Backbone 4
    uploadProgress https://www.customedialabs.com/experience/wp-content/plugins/buddyboss-platform/bp-core/js/avatar.min.js?ver=1.5.6:1
`

The acquire.io chatbot widget conflicts with the BuddyBoss photo upload JS code.

**To Reproduce**
1. Ask me access for our site 
1. Upload a profile photo
4. See console for error

**Expected behavior**
Upload a photo while using acquire.io chatbot

**Comment by marienel21** [comment] 2021-08-17 11:56
Hi @prototype23 

Thank you for adding this issue, however as per the [notes](https://github.com/buddyboss/buddyboss-platform#support), this repository is not suitable for support issues. I’m going to close this ticket but if the problem is still outstanding please submit a support request at your [BuddyBoss.com](https://www.buddyboss.com/) account.

Thanks,
Marienel - BuddyBoss Product Team

**Closed by marienel21** 2021-08-17 11:56 UTC
Labels: bug, priority: medium
