### ISSUE TITLE
Commenting on Media not working when RTMedia is activated

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1967] opened 2020-12-26 14:31 UTC
**Describe the bug**
Commenting on media is throwing an Error when RTMedia is activated.

**To Reproduce**
1. Install RTMedia plugin
2. In RTMedia > Settings > Display > Single Media View = enable Allow user to comment on uploaded media
3. In frontend, Go to Profile and click on the Media tab
4. Upload sample image in Media and try to comment
5. Open the uploaded media again

**Expected behavior**
The commenting should work, this is working on a BuddyPress and non-BuddyBoss Theme setup

**Screenshots**
https://drive.google.com/file/d/1pa7bbuc8NQ26M6xuBDmm5DCp9948KafV/view

Images from Buddypress and non-BB Theme
https://tinyurl.com/y8kacsll
https://tinyurl.com/yaagw2rn

**Support ticket links**
https://secure.helpscout.net/conversation/1377726332/116511

**Comment by jitendrabanjara1991** [comment] 2021-01-22 15:48
Hello @emmanoctaviano 
This issue is not related to our plugin. This issue is related to **rtMedia for WordPress, BuddyPress and bbPress** plugin. So, I am closing this issue.
Thanks.

**Closed by jitendrabanjara1991** 2021-01-22 15:48 UTC
Labels: bug, priority: medium

**Comment by jitendrabanjara1991** [comment] 2021-01-29 14:32
Hello @emmanoctaviano 

This issue is not related to our plugin. This issue is related to **rtMedia for WordPress, BuddyPress and bbPress**. 

**rtMedia for WordPress, BuddyPress and bbPress**  plugin uses one filter of our plugin (**BuddyBoss Platform**). 
Filter name look like this  apply_filters( 'bp_get_activity_content', $comment_string ). 

And we have added one new parameter in this filter which look like this 
apply_filters( 'bp_get_activity_content', $comment_string, $activity ). 

Because of this, it's not working. I have also confirmed in my local system with some changes. For that, you can check the video here. [https://screencast-o-matic.com/watch/crVjFDPvpe](https://screencast-o-matic.com/watch/crVjFDPvpe)

Please let me know if anything else.

Thanks.
