### ISSUE TITLE
Pagination on Forums > Replies page is not working. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#713] opened 2020-04-07 11:20 UTC
**Describe the bug**
The pagination works fine for forums and discussions but doesn't work on the replies page. 

**To Reproduce**
1. Go to Dashboard > BuddyBoss > Forums > set the no. for replies page
2. Open the replies page on the frontend
3. See error

**Expected behavior**
The pagination should work for the replies page. 

**Screenshots**
- https://i.imgur.com/8iSAvc5.jpg
- https://i.imgur.com/nb6mAxO.jpg

**Support ticket links**
- https://secure.helpscout.net/conversation/1127859726/66941?folderId=3701247

**Comment by janakkaneriya007** [comment] 2020-04-08 05:15
@archanabb 
Duplicate of: https://github.com/buddyboss/buddyboss-platform/issues/678

**Closed by janakkaneriya007** 2020-04-08 05:15 UTC
Labels: bug, component: forums, priority: medium
