### ISSUE TITLE
Group invites is telling us "All site members are already members of this group, or have already received an invite to join this group, or have requested to join it." 

### ISSUE THREAD

**Issue by harshadmane** [buddyboss/buddyboss-platform#2186] opened 2021-02-28 02:53 UTC
**Describe the bug**
Group invites is telling us "All site members are already members of this group, or have already received an invite to join this group, or have requested to join it."  when we send invites while creating the group.

**To Reproduce**
1. Go to Groups
2. Click Create a group
3. Complete all the steps and at the send select all members to send invites
4. You'll see a message "All site members are already members of this group, or have already received an invite to join this group, or have requested to join it."

**Expected behavior**
It should not show the message instead send invites to members.

**Screenshots**
https://prnt.sc/108z6e9

**Support ticket links**
https://secure.helpscout.net/conversation/1436135107/127237/

**Comment by marienel21** [comment] 2021-08-13 17:27
I can't reproduce this bug on the latest version of the Platform.

**Comment by surajkrsingh** [comment] 2021-09-21 02:48
@harshadmane @marienel21 
We tested this and were not able to replicate this issue.
See here - https://drive.google.com/file/d/1b4I-3Wj8S_7Q6Bb_Pa9tS_xZ4UsKpD0O/view

@dipskakadiya Can we close this issue?

**Comment by mikejyoung** [comment] 2021-09-23 14:58
Closing issue.

**Closed by mikejyoung** 2021-09-23 14:58 UTC
Labels: bug, bug: can't reproduce
