### ISSUE TITLE
Exclude Profile Field data being cached by Redis Object Cache

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#1417] opened 2020-08-28 16:21 UTC
**Describe the bug**
Profile Field data is being cached by Redis Object Cache Plugin, these must be excluded as the data is being changed frequently.

**To Reproduce**
1. Make sure server is Redis enabled
2. Install Redis Object Cache
3. Create Profile Fields, add them to the default sign up details
4. Enable Redis Object Cache
5. Add Profile Completion Widget on Activity Feed

**Expected behavior**
Profile Fields must be included, though this can be fixed via flushing cache, the Profile Fields must be excluded as this changes frequently

**Screenshots**
https://drive.google.com/file/d/19XR_8QmQQa5Opst6a4xYUMwgaDxQoZZU/view?usp=sharing

**Support ticket links**
https://secure.helpscout.net/conversation/1253848664/88198

**Theme and Platform PRs**
https://github.com/buddyboss/buddyboss-platform/pull/1611
https://github.com/buddyboss/buddyboss-theme/pull/1091

**Comment by chetansatasiya** [comment] 2020-10-09 08:49
https://secure.helpscout.net/conversation/1302455724/102224?folderId=3969503

**Comment by sourabhmatolia** [comment] 2020-10-16 13:51
@chetansatasiya 

**Issues found**

- Add widget > Check progress > Adding/Removing Profile fields doesn’t clear cache for all users on the site. Shows invalid progress.
- Same issue with Elementor
- Elementor settings not working > Profile completion widget hides after 100% progress even when setting to hide is not enabled. It starts to work after settings are toggled.

**Comment by mohit-buddyboss** [comment] 2020-10-16 15:42
> @chetansatasiya
> 
> **Issues found**
> 
> * Add widget > Check progress > Adding/Removing Profile fields doesn’t clear cache for all users on the site. Shows invalid progress.
> * Same issue with Elementor

@chetansatasiya @sourabhmatolia 

**Issue: 1**
I'm able to create issue after fresh set up. 
-Enable redis on server.
-Reinstalled Redis object cache plugin. 
Issue :- When we enable object from plugin then it removes "Profile fields" data from the Profile details. Due to this profile field gets empty. 

Video: https://www.loom.com/share/a150cef63b18479ba0f8282073dfa7f0

**Comment by mohit-buddyboss** [comment] 2020-10-16 15:45
> @chetansatasiya
> 
> * Elementor settings not working > Profile completion widget hides after 100% progress even when setting to hide is not enabled. It starts to work after settings are toggled.

@sourabhmatolia This issue exist on dev server. I already created this issue and @annrra generated PR for this issue. Here is the issue link:  https://github.com/buddyboss/buddyboss-theme/issues/1118

**Comment by chetansatasiya** [comment] 2020-10-19 05:48
> > @chetansatasiya
> > **Issues found**
> > 
> > * Add widget > Check progress > Adding/Removing Profile fields doesn’t clear cache for all users on the site. Shows invalid progress.
> > * Same issue with Elementor
> 
> @chetansatasiya @sourabhmatolia
> 
> **Issue: 1**
> I'm able to create issue after fresh set up.
> -Enable redis on server.
> -Reinstalled Redis object cache plugin.
> Issue :- When we enable object from plugin then it removes "Profile fields" data from the Profile details. Due to this profile field gets empty.
> 
> Video: https://www.loom.com/share/a150cef63b18479ba0f8282073dfa7f0

@mohit-buddyboss I am not able to reproduce above issue as well.

@sourabhmatolia I need the steps to reproduce this issue https://github.com/buddyboss/buddyboss-platform/issues/1417#issuecomment-710060504

**Comment by chetansatasiya** [comment] 2020-10-19 06:24
> > @chetansatasiya
> > **Issues found**
> > 
> > * Add widget > Check progress > Adding/Removing Profile fields doesn’t clear cache for all users on the site. Shows invalid progress.
> > * Same issue with Elementor
> 
> @chetansatasiya @sourabhmatolia
> 
> **Issue: 1**
> I'm able to create issue after fresh set up.
> -Enable redis on server.
> -Reinstalled Redis object cache plugin.
> Issue :- When we enable object from plugin then it removes "Profile fields" data from the Profile details. Due to this profile field gets empty.
> 
> Video: https://www.loom.com/share/a150cef63b18479ba0f8282073dfa7f0

@mohit-buddyboss @sourabhmatolia  Whenever you enable/disable the object cache from backend you need to first **Flush Cache** button before checking anything on the site otherwise it will take from the older memory cache. Let me know if you have any other steps to reproduce.

**Comment by sourabhmatolia** [comment] 2020-10-19 07:45
@chetansatasiya 

Here's how you can replicate the issue:
https://www.loom.com/share/3038097df74140e3a9a68999114b46a6?from_recorder=1

BTW, I did not have any caching enabled. No server settings No plugins.
Missed showing you that in the video.

**Comment by chetansatasiya** [comment] 2020-10-19 08:50
@sourabhmatolia Thanks for the video. Issue is fixed now.

@mohit-buddyboss 

Issue 1 is fixed.
Issue 2 is already fixed in different PR & Issue.

Please retest and let me know if you found anything.

**Comment by mohit-buddyboss** [comment] 2020-10-20 06:59
@chetansatasiya 

FIXED>Tested using `pr/1611` of the platform and `pr/1091` of the theme.
Tested this with and without Redis enable on server and by activating and deactivating Redis object cache Plugin as well as enabling and disabling website object cache. 

Issue 1 :  Profile Field date not updating for all users on website while adding or removing fields. (Resolved)
https://www.loom.com/share/cd3e79993e254428aab9fa118f1af658 
https://www.loom.com/share/0491a681d09c491fbf16a636a619ad5e

Issue 2: Profile fields getting remove when enabling or disabling object cache. (Resolved) 
https://www.loom.com/share/9058edbef7b94615bbe1f58ee49cbeff?from_recorder=1

@sourabhmatolia

**Closed** 2020-11-03 13:08 UTC
Labels: bug, component: profile fields, component: profiles, hacktoberfest, priority: high
