### ISSUE TITLE
When a group is public and it has a forum, anyone can post to it, even though they haven't joined the group.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1301] opened 2020-08-04 05:34 UTC
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by chetansatasiya** [comment] 2020-08-04 05:40
@furqanbb Closing this because if you have this https://prntscr.com/ttlyrs settings enabled then it will allow you to add. If disabled then it will not allow you.

**Closed by chetansatasiya** 2020-08-04 05:40 UTC
Labels: bug, priority: medium

**Comment by chetansatasiya** [comment] 2020-08-04 05:45
Duplicate of https://github.com/buddyboss/buddyboss-platform/issues/1302
