### ISSUE TITLE
buddy boss issue

### ISSUE THREAD

**Issue by femio1** [buddyboss/buddyboss-platform#2630] opened 2021-07-16 18:02 UTC
Received the updates for the BuddyBoss Theme and Plugin today.  updated as usual and within a few minutes site crashed.  Debugged and saw the fatal error message pointing to **wp-content/themes/buddyboss-theme/inc/plugins/bbpress-helper.pho on line 22**
We deleted the line and the website returned. Wondering whether this was a common error or only with our set up.  

Also the developer who intervened on our behalf is complaining that jquery is not functioning properly.  Is there any relationship between what happened with the theme error and this issue that has now arisen. 

If anyone can shed light on the issue I would be very grateful.

**Comment by ThemeMetro** [comment] 2021-07-16 18:15
Same issue with me and the issue which is claimed to fix in 1.7.2.1 still present with me, i must need to enable Forum Component while i am using 1.7.2.2 to make Activity feed.

**Comment by marienel21** [comment] 2021-08-17 11:59
Hi @femio1 

Thank you for adding this issue, however as per the [notes](https://github.com/buddyboss/buddyboss-platform#support), this repository is not suitable for support issues. I’m going to close this ticket but if the problem is still outstanding please submit a support request at your [BuddyBoss.com](https://www.buddyboss.com/) account.

Thanks,
Marienel - BuddyBoss Product Team

**Closed by marienel21** 2021-08-17 11:59 UTC
Labels: bug, bug: needs validating
