### ISSUE TITLE
Wishlist Member can't access Buddyboss Platform protected pages (Activity, groups, members etc) although user have permission to access all pages

### ISSUE THREAD

**Issue by jakir-git** [buddyboss/buddyboss-platform#1514] opened 2020-09-20 11:59 UTC
**Describe the bug**
If you install the "Wishlist Member" plugin and create some membership level and give permission. Then create use and add this user on that Membership level. Now set the Buddyboss Platform pages (Activity, groups, members etc) access mode to protected. Then when this user tries to visit those pages they can't access that page but can access all other page like sample page.

[ NB: Not enable Buddyboss private network ]

See all this screenshot

https://prnt.sc/ukifsy
https://prnt.sc/ukif9a
https://prnt.sc/ukikhn
https://prnt.sc/ukie6v

**To Reproduce**
1. Install Wishlist Member and create membership level like this 
https://prnt.sc/ukifsy
2. Create a user and assign the user to that membership level
https://prnt.sc/ukif9a
3. Now set the Buddyboss Platform pages (Activity, groups, members etc) access mode to protected. 
https://prnt.sc/ukikhn
4. See this
https://prnt.sc/ukie6v

**Expected behavior**
Should can access all the Buddyboss pages.

**Support ticket links**
https://secure.helpscout.net/conversation/1284512201/99137?folderId=3955985

**Comment by janakkaneriya007** [comment] 2020-11-25 09:05
@jakir-git 

I have checked and found that the issue is not from our plugin.
I have contacted the Wishlist Member plugin developer and he said that they will fix this issue in their next release.
closing issue for now.

**Closed by janakkaneriya007** 2020-11-25 09:05 UTC
Labels: bug, priority: medium
