### ISSUE TITLE
Replies per page setting is not working.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#2513] opened 2021-06-17 08:17 UTC
**Describe the bug**
When changing the setting for replies per page, it doesn't work. Forums per page and discussion per page setting works fine.

**To Reproduce**
http://somup.com/cr1bjDq5ND

**Support ticket links**
https://secure.helpscout.net/conversation/1542781624/147674?folderId=3701248

**Comment by roopeshbuddyboss** [comment] 2021-07-12 06:23
Hi @furqanbb ,

I have checked this issue with the latest plugins and BB-theme and demos too and I could not replicate the issue. Can you please check the attached video and let me know if you finding something?

https://www.loom.com/share/745329470659448ebbdf164ee9734597

Thanks

**Comment by furqanbb** [comment] 2021-07-24 09:58
@RoopeshBahree Yes, I tested it with the latest version and it is working fine now. We can close this one.

**Comment by roopeshbuddyboss** [comment] 2021-07-26 04:35
Hi,

Closing this as the issue is not there with the latest platform.

Thanks

**Closed by roopeshbuddyboss** 2021-07-26 04:35 UTC
Labels: bug, bug: needs validating
