### ISSUE TITLE
Issue when sending a message privately to every individual in group with lot of members

### ISSUE THREAD

**Issue by aravindshetty21** [buddyboss/buddyboss-platform#3027] opened 2021-10-06 15:22 UTC
**Describe the bug**
When I send a private message to every individual in the group, the message won't go. The ajax call doesn't gets complete and I can see the response as "There is a critical error in your website ... ". When I check the error log, I can see a fatal error that the PHP execution time limit has exceeded. When I increased the time limit, It takes a very long time to send the message to everyone. It is taking an hour to send the message to 300 members in the group.

**To Reproduce**
1. Create a group with lot of members like 300 members
2. Open the group
3. Go to send messages > send privately
4. select everyone in the group and click send.

**Expected behavior**
I expect the message should be sent to everyone in a couple of seconds. But if possible I would like an interim solution that the message could be sent to everyone in less than 5 mins.

**Comment by chetansatasiya** [comment] 2021-10-11 04:42
Duplicate of https://github.com/buddyboss/buddyboss-platform/issues/2587 closing this one.

**Closed by chetansatasiya** 2021-10-11 04:42 UTC
Labels: bug, bug: needs validating
