### ISSUE TITLE
New contacts should automatically follow each other

### ISSUE THREAD

**Issue by TokumeiJG** [buddyboss/buddyboss-platform#1698] opened 2020-10-27 05:18 UTC
**Describe the bug**
Becoming a contact/friend with a user does not automatically follow that user.

**To Reproduce**

1. Go to a user you are not friends with
2. Add them as a contact (but not follow)
3. User accepts contact request
4. Contacts are now connected but **not** following each other

**Expected behavior**
This may be the original BuddyPress behavior but it is confusing to users as to why they are not following their contacts.

**Comment by ExoGeek** [comment] 2020-10-27 09:17
Personally, I prefer let that as it is now. Friend connection means that 2 persons "know" each other. But following means that the person has a really interest in what the other person is posting.

In my case, I like to have that 2 notions separated.

**Comment by TokumeiJG** [comment] 2020-10-27 10:29
Yes, I understand there are certain cases where you want them separate (like I follow Elon Musk on Twitter - completely one sided!) but for a non-techie crowd the idea of the two being different seems a bit hard.
They get friends (ie Facebook) and following one-sided (ie Twitter), but the idea of being friends _but not following_ seems to be the part they get stuck on...

It doesn't need to be a default, but maybe an option in contacts settings?
- Users automatically follow each other when becoming contacts (Yes/No)

**Comment by bb-yudhisthir** [comment] 2021-09-14 03:48
@ExoGeek @TokumeiJG

Connection(friends) vs Follow is completely different feature and as mentioned by @ExoGeek already, also this its the default behavior and is implemented the way it is so this is not a bug.

Also the "follower" doesn’t need to be approved by the one he follows. while for “Friends” to connect completely friendship request must be approved by the other party.

For the feature request, you may need to go to https://www.buddyboss.com/roadmap/ and add the feature request, for now I have created the one already on your behalf, as this is not a bug so closing this issue.

**Closed by bb-yudhisthir** 2021-09-14 03:48 UTC
Labels: bug, priority: medium, bug: validated

**Comment by ExoGeek** [comment] 2021-09-14 07:02
@TokumeiJG If Following and Friendship is the "same" notion for you, I suggest that you simply disable the following feature. You can do it in the BuddyBoss settings.
