### ISSUE TITLE
Group Message - Line break and repetitive message

### ISSUE THREAD

**Issue by jrbuddyboss** [buddyboss/buddyboss-platform#1577] opened 2020-09-30 22:07 UTC
Describe the bug
When sending a message in a group, the line break didn't apply and when clicking the send message button thrice, it also sent thrice.

To Reproduce

Go to group page
Click one of the group
Send a message to that group.
Go to your inbox and check that message. See the error.
Expected behavior
Sending message in a group with line break should have formatted accordingly.
Clicking the send message button thrice should sent once.

Screenshots
https://www.loom.com/share/c9a843733d1b4101ba3278f3ce41bf0d

Support ticket links
https://secure.helpscout.net/conversation/1294300586/100944
https://secure.helpscout.net/conversation/1290282969/100195

**Comment by justinpatrickkeller** [comment] 2020-10-02 01:51
This is a duplicate of https://github.com/buddyboss/buddyboss-platform/issues/1558. 

Additionally, I have identified that this issue is causing words to be concatenated onto links in a message resulting in broken links.

**Closed** 2020-10-02 10:34 UTC
Labels: bug, priority: medium

**Comment by sourabhmatolia** [comment] 2020-10-18 04:04
@justinpatrickkeller 

Issue created above is released in Buddyboss Platform v1.5.3.

Please find release notes here:
https://www.buddyboss.com/resources/buddyboss-platform-releases/1-5-3/

Please update the plugin to see the latest changes.

Thank you.
