### ISSUE TITLE
LearnDash Multisite setup -  Start Course button is redirecting to all course when you view it via Groups

### ISSUE THREAD

**Issue by emmanoctaviano** [buddyboss/buddyboss-platform#611] opened 2020-03-02 16:37 UTC
**Describe the bug**
on multisite setup, When a single course is added on a LearnDash Group synched to a BuddyBoss Group, the Start Course button is not working when you view it via Groups > Courses tab

**To Reproduce**
1. Create a multisite setup, install LearnDash 3.1.3, BuddyBoss Platform 1.2.7 and BuddyBoss Theme 1.3.7
2. Create a LearnDash Group and synch it with a BuddyBoss Group
3. Create a Course (with sample lessons)
4. Add the created Course to the LearnDash Group
5. On a different browser, log in as a subscriber and add your self to the created Group
6. On the frontend, go to Groups > Course tab and click on Course
7. Click on Start Course and see error
8. When you add another Course to that Group, this is working

**Expected behavior**
This will redirect to the continuation or start of course instead of redirecting to ALL COURSES

**Screenshots**
https://drive.google.com/open?id=1baM9pV6ZwQceKxMFRzBGt0Bc0gH4z-em

**Support ticket links**
https://secure.helpscout.net/conversation/1111951933/3758/

**Comment by shohelbuddyboss** [comment] 2020-07-23 14:52
I checked it with a long time, but couldn't reproduce the issue.

**Comment by chetansatasiya** [comment] 2020-07-23 14:53
@emmanoctaviano Can you look it again and if this stil reproducalbe help @shohelbuddyboss to reprodice?

**Comment by chetansatasiya** [comment] 2020-07-30 13:10
@emmanoctaviano I am closing this issue so please reply to customer like it's fixed in our previous release.

**Closed by chetansatasiya** 2020-07-30 13:10 UTC
Labels: bug, can't reproduce, component: groups, learndash, priority: high
