### ISSUE TITLE
When a group is public and it has a forum, anyone can post to it, even though they haven't joined the group.

### ISSUE THREAD

**Issue by furqanbb** [buddyboss/buddyboss-platform#1302] opened 2020-08-04 05:34 UTC
**Describe the bug**
When a group is public and it has a forum, anyone can post to it, even though they haven't joined the group. 
This issue occurs if you change the /forum/ slug to something else.

**To Reproduce**
1. Go to 'BuddyBOss >> Settings >> Forums' and change the forum slug.
http://prntscr.com/ttlkbq
2. Now open a Public group without joining the group and navigate to Discussion tab.
3. See, you can add a reply to the discussion without joining the group.

**Expected behavior**
If the user has not joined the group he should not be able to post to a discussion.

**Screenshots**
http://prntscr.com/ttlkbq

**Support ticket links**
https://secure.helpscout.net/conversation/1237485299/85307?folderId=3701248

**Comment by chetansatasiya** [comment] 2020-08-04 05:38
Duplicate of https://github.com/buddyboss/buddyboss-platform/issues/1301

**Closed** 2020-10-30 12:08 UTC
Labels: bug, hacktoberfest, priority: medium, status: needs review
