### ISSUE TITLE
Updating the platform throws FATAL error - Solved. 

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#864] opened 2020-05-07 12:31 UTC
**Describe the bug**
Updating the platform throws FATAL error - The issue is already solved by the user. Please review the solution. Following is the copy of the content from the email received:

There was an issue with the wp-config.php - there was this error at the top:

**_JWT_AUTH_SECRET_KEYTsdfsdfsd234_**

It was just a text string sitting there. There was other lines like this:

**_define('JWT_AUTH_SECRET_KEY', 'ef332f787d95ce44e6eb3a413f5e3733');
define('JWT_AUTH_CORS_ENABLE', true);_**

Those are ok.

So a change has been made here: **_/htdocs/wp-content/plugins/buddyboss-platform/bp-templates/bp-nouveau/buddypress/search/loop/topic-ajax.php_**

Instead of:

`$tags_count = count($discussion_tags);`

It's now:

```
if (is_countable($discussion_tags)){
$tags_count = count($discussion_tags);
} else {
$tags_count = 0;
}
```

**Support ticket links**
https://secure.helpscout.net/conversation/1157235532/72224/

**Comment by janakkaneriya007** [comment] 2020-05-07 12:36
@archanabb 

Duplicate of: https://github.com/buddyboss/buddyboss-platform/issues/862

**Comment by chetansatasiya** [comment] 2020-07-10 06:36
Closing this as duplicate of #862

**Closed by chetansatasiya** 2020-07-10 06:36 UTC
Labels: bug, can't reproduce, priority: medium
