### ISSUE TITLE
Messaging

### ISSUE THREAD

**Issue by thejewishblt** [buddyboss/buddyboss-platform#2039] opened 2021-01-13 19:06 UTC
We have built a custom theme and can not get the messaging and activity icons in the menu to pull into the fields with dynamic numbers like the normal theme they have. Any advice would be great.

**Comment by marienel21** [comment] 2021-08-17 11:54
Hi @thejewishblt 

Thank you for adding this issue, however as per the [notes](https://github.com/buddyboss/buddyboss-platform#support), this repository is not suitable for support issues. I’m going to close this ticket but if the problem is still outstanding please submit a support request at your [BuddyBoss.com](https://www.buddyboss.com/) account.

Thanks,
Marienel - BuddyBoss Product Team

**Closed by marienel21** 2021-08-17 11:54 UTC
