### ISSUE TITLE
Reported Topic related activity should be hide.

### ISSUE THREAD

**Issue by parmarhardip** [buddyboss/buddyboss-platform#2732] opened 2021-08-05 05:20 UTC
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
1. Go to 'Create topic'
2. Created topic activity 
3. Reported that topic
4. Go to activity list and click that topic activity.
5. See error

**Expected behavior**
If topic reported and hide that topic so related activity topic should be hide.

**Screenshots**
![image](https://user-images.githubusercontent.com/23077242/128294944-dac0d4d0-54fd-47c9-8eb6-8cabdefc1ad7.png)

![image](https://user-images.githubusercontent.com/23077242/128294924-10aa13b4-51a0-4763-8c1c-814ed9e55dda.png)

![image](https://user-images.githubusercontent.com/23077242/128294993-81e73bf2-61f7-4556-959d-a28f05bf5acf.png)

https://user-images.githubusercontent.com/23077242/128295152-f7d1e2d3-be25-466e-b45f-923cb6a171cd.mov

**Environment**
Which site did you replicate this issue on?

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.
Buddyboss App issue link: https://github.com/buddyboss/buddyboss-app/issues/2349

**Comment by bb-yudhisthir** [comment] 2021-11-08 11:27
@parmarhardip I am unable to replicate the issue when the forum topic is reported and hidden then the related activity is also hidden. Let me know if anything is missing
http://somup.com/crXjX33PLV

**Comment by bb-yudhisthir** [comment] 2021-11-09 05:42
@parmarhardip Checked with the private forum too still the "created new discussion" activity for that topic is hidden from the activity as soon as the topic is reported and hidden and so unable to reproduce it, so closing the issue

**Closed by bb-yudhisthir** 2021-11-09 05:42 UTC
Labels: bug, bug: can't reproduce, component: moderation
