### ISSUE TITLE
Mobile Menu Button Doesn't Work with Our FLV Player

### ISSUE THREAD

**Issue by harshadmane** [buddyboss/buddyboss-platform#2273] opened 2021-03-25 03:12 UTC
**Describe the bug**
Mobile Menu Button Doesn't Work with Our Video Player

**To Reproduce**
1. Go to https://rhythmjuice.com/mobile-menu-bug/ on mobile
2. Click the mobile menu and search button it should open
3. Now play the video
4. Now click the mobile menu and click search icon it should not open.
5. FLV player authors provided some troubleshooting steps in BuddyBoss code: https://foliovision.com/support/fv-wordpress-flowplayer/bug-reports/site-menus-not-working-after-wordpress-upgrade-to-5-6#post-126946

**Expected behavior**
The mobile menu should work when FLY player is opened

**Screenshots**
Video: https://www.loom.com/share/ffb3e33e361a4c3a8f6b87925a480b59

**Support ticket links**
https://secure.helpscout.net/conversation/1458338272/131548?folderId=4304220

**Comment by marienel21** [comment] 2021-09-07 17:22
I can't reproduce this bug.

**Comment by surajkrsingh** [comment] 2021-09-21 02:35
@harshadmane @marienel21 
I m also not able to reproduce this issue on the customer site and 
if this is FV player pro specific then we don't have this in our support list.


@dipskakadiya Can we close this issue?

**Comment by mikejyoung** [comment] 2021-09-23 14:58
Closing issue.

**Closed by mikejyoung** 2021-09-23 14:58 UTC
Labels: bug, bug: can't reproduce
