### ISSUE TITLE
PHP 7.4   Compatibility - foreach no longer changes the internal array pointer

### ISSUE THREAD

**Issue by davidmabelle** [buddyboss/buddyboss-platform#1736] opened 2020-11-04 21:43 UTC
Please scan and update all code references to foreach to be compatible with 7.4

**Comment by davidmabelle** [comment] 2020-11-06 00:25
Warning: Invalid argument supplied for foreach() in /kunder/gmailc_10514/cocrea_13235/public/wp-content/plugins/buddyboss-platform/bp-core/admin/bp-core-admin-theme-settings.php on line 26

**Comment by krunal-buddyboss** [comment] 2020-11-17 12:01
Hello @davidmabelle 

I have checked foreach at `buddyboss-platform/bp-core/admin/bp-core-admin-theme-settings.php on line 26`, it already compatible with PHP 7.4 version and also other foreach are compatible with PHP 7.4 version. 
Please update the BuddyBoss Platform plugin and theme and check once. Looks like you are checking on older version of the BuddyBoss Platform plugin and theme.

Thanks.

**Comment by dkvasani** [comment] 2020-12-28 03:43
Hi @davidmabelle 

I have checked but I am not able to reproduce this issue.

**Comment by dkvasani** [comment] 2021-01-01 14:17
Hi @sourabhmatolia
As Discussed with you i am not replicat this issue so i am closing this issue.

**Closed by dkvasani** 2021-01-01 14:17 UTC
Labels: bug, can't reproduce, priority: medium
