### ISSUE TITLE
Document preview is not working when Insert or Embed Articulate Content into WordPress plugin is enabled

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#1368] opened 2020-08-17 19:53 UTC
**To Reproduce**
1. Install and activate **Insert or Embed Articulate Content into WordPress** plugin
2. Go to the document page and upload a file.
3. Open the file and notice that the preview is not working

**Screenshots**
![error1](https://user-images.githubusercontent.com/58522498/90437946-cede9080-e105-11ea-8736-6969ae5109c4.jpg)
![error2](https://user-images.githubusercontent.com/58522498/90437947-cede9080-e105-11ea-80cf-e4dacf4dd623.jpg)

**PHP Error log**
`PHP Fatal error:  Cannot redeclare bp_nouveau_document_enqueue_scripts() (previously declared in \wp-content\plugins\buddyboss-platform\bp-templates\bp-nouveau\includes\document\functions.php:19) in \wp-content\plugins\buddyboss-platform\bp-templates\bp-nouveau\includes\document\functions.php on line 28`

**Support ticket links**
https://secure.helpscout.net/conversation/1222676086/82926

**Comment by elearningplugins** [comment] 2021-02-03 18:26
Thanks for reporting the issue @ayron-paul - I've resolved the compatibility issue in the Articulate plugin.  

The issue is resolved in version 4.3000000005 that was released on February 3rd, 2021.

It'll also be resolved in the premium plugin when I do the next update in the coming weeks.

**Comment by therajumandapati** [comment] 2021-03-25 14:36
@elearningplugins What was the actual fix? Did you change `require ` to `require_once`? We're also having this issue on a BuddyBoss environment, but we're not using [Insert or Embed Articulate Content into WordPress](https://wordpress.org/plugins/insert-or-embed-articulate-content-into-wordpress/) plugin.

**Comment by therajumandapati** [comment] 2021-03-25 14:45
@elearningplugins We hotfixed this on our server by directly updating the `require` statements at `https://github.com/buddyboss/buddyboss-platform/blob/release/src/bp-templates/bp-nouveau/includes/document/loader.php#L46` to `require_once`

**Comment by elearningplugins** [comment] 2021-03-25 20:10
> @elearningplugins What was the actual fix? Did you change `require ` to `require_once`? We're also having this issue on a BuddyBoss environment, but we're not using [Insert or Embed Articulate Content into WordPress](https://wordpress.org/plugins/insert-or-embed-articulate-content-into-wordpress/) plugin.

The issue that I resolved was specific to my plugin.  I didn't make any changes specific to the buddyboss plugin.

**Comment by hercivalbuddyboss** [comment] 2021-04-19 14:00
Supporting Ticket : [https://secure.helpscout.net/conversation/1478918001/135424](https://secure.helpscout.net/conversation/1478918001/135424)

**Comment by mahedihasannoman** [comment] 2021-09-14 12:59
Hi @ayron-paul This is not an issue with BuddyBoss Platform. Also the issue has been fixed in  Insert or Embed Articulate Content into WordPress plugin itself. You can close this ticket.

**Closed** 2021-09-17 13:16 UTC
Labels: bug, priority: medium, bug: validated
