### ISSUE TITLE
Images in activity feeds not being allowed to have their URLs replaced with the CDN URL

### ISSUE THREAD

**Issue by tamara-m** [buddyboss/buddyboss-platform#1391] opened 2020-08-23 18:30 UTC
**Describe the bug**
Images are not being loaded from the CDN in activity feeds. The same images, uploaded in a Forum thread, load through the CDN when viewed in the Forum thread page example.com/forums/thread/my-thread. But when loaded in an activity feed, they are loading from the server URL instead of the CDN URL.

**To Reproduce**
1. Implement any CDN
2. Upload an image to a Forum post or post to the main activity feed - both produce the same result
3. Visit the main Activity feed and inspect with your browser tools the <img> inside the a element with class="bb-open-media-theatre entry-img"
4. See how they load from the site URL instead of the CDN URL

**Expected behavior**
Like all other images in the site, that get the server media URLs replaced with the CDN URLs successfully, I would expect images in Activity feeds from adopting the same behavior.

**Screenshots**
Image in forum thread, correctly loading from the CDN
![HVjZTnAuoM](https://user-images.githubusercontent.com/9288041/90985918-66ecd780-e555-11ea-8f38-2948ed8df405.jpg)

Same image in Activity feed, loading from the site.
![7nirkt6eON](https://user-images.githubusercontent.com/9288041/90985925-6d7b4f00-e555-11ea-8c85-9127f7c8e167.jpg)

**Support ticket links**
The client owns a paid license of the theme+platform bundle, let me know please if you prefer this ticket to be handled through their account. Thank you!

**Comment by chetansatasiya** [comment] 2021-09-01 08:30
@tamara-m I am not facing any issue right now. Can you check with the latest version and see if the issue is still persisit. I am closing this issue and feel free to reopen if the issue persist.

**Closed by chetansatasiya** 2021-09-01 08:30 UTC
Labels: bug, priority: medium
