### ISSUE TITLE
Group members can't see their hidden group on the Group Directory.

### ISSUE THREAD

**Issue by imehedidev** [buddyboss/buddyboss-platform#1196] opened 2020-07-14 08:56 UTC
**Describe the bug**
Group members can't see their hidden group on the Group Directory page. It works when the group privacy is public and private.

**To Reproduce - Video Explanation**
Steps to reproduce the behavior: https://www.loom.com/share/006b8e3741e841bbbcbdf1fbab087e7e

**Expected behavior**
Group members should see their hidden groups.

**Support ticket links**
https://secure.helpscout.net/conversation/1218549643/82261

**Comment by mehulkaklotar** [comment] 2020-07-15 07:21
@imehedidev @shohelbuddyboss This is not a bug. Hidden means hidden from site. it should not show in groups directory. But if you go to `My Groups` it shows your all groups you are part of.

**Comment by eisenwasser** [comment] 2020-07-16 01:49
@imehedidev 

Mehul is correct. See https://prnt.sc/timnk1

Closing this issue.

**Comment by eisenwasser** [comment] 2020-07-16 04:37
@mehulkaklotar I spoke to @imehedidev and we agreed to re-open this and work on it. Group activity from hidden groups shows in main activity index, we should follow same logic in groups and be consistent. hidden groups are hidden from groups directory... unless you are a member of the group

**Closed** 2020-10-02 14:10 UTC
Labels: bug, component: groups, feature: enhancement, priority: high, status: needs review, status: needs testing

**Comment by joanne-21** [comment] 2022-02-25 06:36
Hi, i have the latest version of Buddy Boss platform free version. But i am still having this issue on my site. Group members of the hidden group can't see the group in their 'My Groups'
