### ISSUE TITLE
Duplicate entries being created under "View Report" in moderation tab

### ISSUE THREAD

**Issue by janakkaneriya007** [buddyboss/buddyboss-platform#2733] opened 2021-08-05 06:20 UTC
**Describe the bug**
When reporting any item it is creating two entries with the same reported in the backend which is logically incorrect as one user can only report an item only one time.

**To Reproduce**
1. Go to frontend and report any item
2. Check the reported item
3. Sometimes it is creating two same entries with the same reporter

**Expected behavior**
There should be one reporter for the moderation item.

**Screenshots**
https://loom.com/share/8909e3f976a246c2b81d5adda0581d48

**Environment**
Which site did you replicate this issue on?

**Support ticket links**
If applicable, add HelpScout link or ticket number where the issue was originally reported.

**Comment by marienel21** [comment] 2021-08-18 19:50
I can't reproduce this on the latest version of the Platform. Tested in demo.

**Comment by kent-carlo** [comment] 2021-09-20 12:55
@mohit-buddyboss confirmed that he is unable to replicate the issue anymore, closing this.

**Closed by kent-carlo** 2021-09-20 12:55 UTC
Labels: bug, bug: can't reproduce, component: moderation
