### ISSUE TITLE
RE: How to redirect default profile to another page

### ISSUE THREAD

**Issue by supermelon600** [buddyboss/buddyboss-platform#1440] opened 2020-09-02 23:37 UTC
Hi!

I'm trying to figure out how to redirect a user from the default profile url to another profile page on a new url that I will make.

How can I set the new url of the new profile page to include their username?

**Comment by marienel21** [comment] 2021-08-17 11:52
Hi @supermelon600 

Thank you for adding this issue, however as per the [notes](https://github.com/buddyboss/buddyboss-platform#support), this repository is not suitable for support issues. I’m going to close this ticket but if the problem is still outstanding please submit a support request at your [BuddyBoss.com](https://www.buddyboss.com/) account.

Thanks,
Marienel - BuddyBoss Product Team

**Closed by marienel21** 2021-08-17 11:52 UTC
