### ISSUE TITLE
Event loading issue with latest version of BB Platform in Network admin

### ISSUE THREAD

**Issue by shyamwp14** [buddyboss/buddyboss-platform#2424] opened 2021-05-23 08:22 UTC
**Describe the bug**
In Event manager, event is loading fine with Buddyboss platform 1.5.8.3  version, but when we updated BB platform version to 1.5.9, then event loading issue occur.

**To Reproduce**
1. Go to Event pages, 
2. Click on 'any view event'
3. After updating Buddyboss platform 1.5.8.3  version to 1.5.9
4. See loading error

**Expected behavior**
After updating the BB platform version  15.9, the event should be working.

**Screenshots**
https://prnt.sc/13ao077
https://ibb.co/DzsBphX
https://ibb.co/M7yLczY

**Support ticket links**
https://secure.helpscout.net/conversation/1508544200/141402/

**Comment by kent-carlo** [comment] 2021-06-28 15:43
The error is in buddyboss-platform\bp-core\bp-core-catchuri.php in function **bp_core_change_privacy_policy_link_on_private_network**. Specifically with apply_filters for 'the_content'. Using that filter maybe conflicts with Events Manage plugin in that part. So temp fix is to unset ToS and PP
![image](https://user-images.githubusercontent.com/82648504/123665210-a74e6d80-d86a-11eb-9e43-4dfa813f3791.png)

**Comment by grahamhoffman** [comment] 2021-07-08 03:10
Hello,
I'm the developer of the WP plugin Events Manager

I wanted to report a bug regarding an issue with your privacy policy page code. With that enabled, it causes conflicts in our plugin. A customer states you've said the issue is on our side, and graciously created some PHP code to fix it. However, looking at the code I could track down the problem back to you actually. I'll explain.

You're using the_content incorrectly when meddling with the privacy policy link page filter, triggered by the WP get_the_privacy_policy_link() function.

Case and point, here's a snippet taken out from the wordpress.org the_content documentation with one very minor tweak and an extra line/comment which can be uncommented to make it work. No EM code is used here and can be reproduced with EM disabled. If you pasted this into your functions.php page or a separate php file in your mu-plugins folder, any regular WP page will crash too:

add_filter( 'the_content', 'filter_the_content_in_the_main_loop', 1 );
function filter_the_content_in_the_main_loop( $content ) {
   // Check if we're inside the main loop in a single Post.
   if ( is_singular() && in_the_loop() && is_main_query() ) {
      // uncomment the line below to make it work with BuddyBoss.
      //remove_filter( 'the_privacy_policy_link', 'bp_core_change_privacy_policy_link_on_private_network', 999999 );
      return $content . get_the_privacy_policy_link();
   }
   return $content;
}

I'm adding my fix above for now in our code to avoid headaches, but I hope you can fix this on your side too. You should make sure take yourselves out of the main loop and make sure global $post the $post object you're loading whilst meddling with the_content.

Best Regards,
Marcus Sykes
Events Manager Lead Developer

**Comment by ayron-paul** [comment] 2021-07-29 14:18
https://secure.helpscout.net/conversation/1561430933/151006/

**Comment by mahedihasannoman** [comment] 2021-07-30 19:24
Hi @shyamwp14 , Can't reproduce with the latest version of Event Manager plugin. Seems like they have changed their plugin code and added the fix on Event Manager plugin. See the screenshot: 
![screenshot-nimbus-capture-2021 07 31-01_22_02](https://user-images.githubusercontent.com/12556175/127702102-1a81994c-2b37-4ab4-bde6-febb37d83921.png)
@shyamwp14 please check with the latest version of EM plugin and if the issue is not happening then please close this ticket.
Thanks

**Comment by ayron-paul** [comment] 2021-08-01 04:09
Hi @mahedihasannoman, as mentioned with Graham's comment, a temporary fix was applied by the developer of the Events Manager plugin, it will be removed once it is fixed from our end.

You may also refer to this ticket https://secure.helpscout.net/conversation/1561430933/151006/.

**Closed** 2021-09-01 10:14 UTC
Labels: bug, priority: high, integration: missing
