### ISSUE TITLE
Notification issue > Wrong name displayed when the user reply to reply in the discussion

### ISSUE THREAD

**Issue by rmmehta** [buddyboss/buddyboss-platform#2777] opened 2021-08-12 12:21 UTC
**Describe the bug**
when any user replay to the replay in the discussion not form the reply button then it's show the Wrong name. It's show the wrong name in the notification text only in the reply it shown the correct name.

**To Reproduce**
1. Go to 'forum'
2. Click on  'any discussion'
3. Click on 'reply text not on reply button' give the replay and now check the main user notification who create the discussion 
4. In the notification you show the different name

**Expected behavior**
It show correct user name in the notification as well.

**Screenshots**
https://prnt.sc/1n4lhs6 

Please refer this video for more explanation: http://somup.com/crjlXnY7wb

**Environment**
I have replicate this issue in my dev site.

**Support ticket links**
https://secure.helpscout.net/conversation/1598640270/158266/

**Comment by grahamhoffman** [comment] 2021-08-17 11:41
Duplicate of #2776

**Closed by grahamhoffman** 2021-08-17 11:41 UTC
Labels: bug, bug: needs validating
