### ISSUE TITLE
"/" character  appears after the text has been updated.

### ISSUE THREAD

**Issue by shyamgudadhe** [buddyboss/buddyboss-platform#2813] opened 2021-08-22 11:14 UTC
**Describe the bug**
We are experiencing an "/" character  appears issue with updating the text on the profile field and some translation on the site

**To Reproduce**
1. Go to 'Buddyboss > Profile
2. Click on 'Add New text field'
3. Then add some Slovak language text in "Instructions" option

Also if we can add this given below text in "Instructions" option
odporúčaný tvar: krstné "meno-priezvisko"
Povolené sú len písmená "a-z", čísla "0-9" a znaky "- _  .". Znaky sa nemôžu opakovať dvakrát. Identifikátor musí obsahovať minimálne 3 a maximálne 32 znakov.

Also we noticed that in Email templates there are strange quotes displayed  with Slovak language e.g. the first email:
[{{{{site.name}}}] Group Membership Request: {{{group.name}}
there are three characters on the left {{{{ and there are only two characters on the right }}]]
**Screenshots**
https://ibb.co/WvMrBwc

**Expected behavior**
When Slovak language text added in "Instructions" option, it should not appear "/" character while updating

**Screenshots**
https://www.loom.com/share/9bf273d5ea4745868c8cc1fa80bfcf1a
https://prnt.sc/1qeg865

**Environment**
Buddyboss Comminity Demo site

**Support ticket links**
https://secure.helpscout.net/conversation/1599432360/158403

**Comment by milanhirapra** [comment] 2021-09-07 14:39
It's the same and solved: https://github.com/buddyboss/buddyboss-platform/issues/2236

**Comment by harshalQA** [comment] 2021-09-13 05:33
Not fixed: Retested on site url : https://bb-app-platform.flywheelsites.com/wp-admin/admin.php?page=bp-profile-setup&mode=edit_field&group_id=1&field_id=14395#tabs-1

Video: https://www.loom.com/share/0f3c45c4e7ae43c784ae9dd78041aa75

**Comment by imehedidev** [comment] 2021-09-13 05:45
Duplicate of #2236

**Closed by imehedidev** 2021-09-13 05:45 UTC
Labels: bug
