### ISSUE TITLE
Plugin Menu not show in WordPress Dashboard

### ISSUE THREAD

**Issue by aamirranja555** [buddyboss/buddyboss-platform#2056] opened 2021-01-18 17:29 UTC
Hi!
I am using the Free plugin BuddyBoss latest version. But I face some issues. Kindly help me to fix this.
1. Menue link does not show in WordPress dashboard
2. Create a forum topic form not show proper

you can check it at psychologyroots.com/community
I try to create a ticket on your website but I unable to find the register option. so kindly reply soon

**Comment by marienel21** [comment] 2021-08-17 11:55
Hi @aamirranja555 

Thank you for adding this issue, however as per the [notes](https://github.com/buddyboss/buddyboss-platform#support), this repository is not suitable for support issues. I’m going to close this ticket but if the problem is still outstanding please submit a support request at your [BuddyBoss.com](https://www.buddyboss.com/) account.

Thanks,
Marienel - BuddyBoss Product Team

**Closed by marienel21** 2021-08-17 11:55 UTC
