### ISSUE TITLE
A lot of preview-image-folder-... folders in uploads directory 

### ISSUE THREAD

**Issue by AiratHalitov** [buddyboss/buddyboss-platform#1005] opened 2020-06-09 22:05 UTC
**Describe the bug**
`/wp-content/uploads/` folder has a lot of `preview-image-folder-...` folders. They all have the same content (preview of PDF file) and have 777 (full access) privileges.

**To Reproduce**
1. Try to upload PDF file to Documents
2. Open `/wp-content/uploads/` folder in file manager
3. You will see +3 new similar folders (`preview-image-folder-...`) with the same content (size also the same)
![image](https://user-images.githubusercontent.com/4050715/84206557-d4e24080-aac8-11ea-9644-db5496786315.png)

**Expected behavior**
I thinks it's a temporary folders and they are should be deleted. 
Because in `bb_documents` folder already have generated images for preview for uploaded PDF files.
![image](https://user-images.githubusercontent.com/4050715/84206191-12929980-aac8-11ea-833a-48cb199e8ccd.png)

Or if they are really needed, then they should be located in the `bb_documents` folder and it should be only one folder for one file (not 3 identical folders).

- buddyboss-platform 1.4.1

**Comment by chetansatasiya** [comment] 2020-06-10 02:51
@AiratHalitov Thanks for the reporting this issues and those folders should be automatically deleted when pdf uploaded into the server. Somehow in your case it didn't deleting. 

Can you update the Platform plugin to the latest relase 1.4.2 and let us know if new PDF uploaded that folder still their or not?

**Comment by chetansatasiya** [comment] 2020-06-10 03:01
@AiratHalitov You can delete those folders manually from your server and we are not using those folders for the previewing the PDF.

There should be a in 1 case that folder is not deleting however after the upgrade of the Platfrom to the 1.4.2 and if the issue is still their then can you add this https://github.com/buddyboss/buddyboss-platform/pull/1006 patch and let me know if the issue is still their.

**Comment by AiratHalitov** [comment] 2020-06-10 10:56
@chetansatasiya 

> Can you update the Platform plugin to the latest relase 1.4.2 and let us know if new PDF uploaded that folder still their or not?

v1.4.2
Only one new folder in `uploads` directory. `preview-image-folder-...` was not deleted automatically.
![image](https://user-images.githubusercontent.com/4050715/84259668-40142d00-ab32-11ea-8c71-fe075b4eadd5.png)

After deleting the PDF file `preview-image-folder-...` was not deleted.

`bb_documents` folder:

![image](https://user-images.githubusercontent.com/4050715/84259692-4acec200-ab32-11ea-9086-d402dd56b4a1.png)

**Comment by chetansatasiya** [comment] 2020-06-10 11:03
@AiratHalitov 

Thanks for looking into it. Now remove that folder again and add this patch https://github.com/buddyboss/buddyboss-platform/pull/1006/files to plugin and upload a new pdf and see folder is still their or not.

**Comment by AiratHalitov** [comment] 2020-06-10 11:21
@chetansatasiya

Patch #1006 deleted `preview-image-folder-...`
but now I don't see a preview of PDF file 
![image](https://user-images.githubusercontent.com/4050715/84261068-98e4c500-ab34-11ea-9abc-331aa7555142.png)

![image](https://user-images.githubusercontent.com/4050715/84262040-5328fc00-ab36-11ea-8aac-06c7faf69e13.png)

![image](https://user-images.githubusercontent.com/4050715/84262067-5f14be00-ab36-11ea-99e7-4ea105bf3695.png)

**Comment by AiratHalitov** [comment] 2020-06-10 11:40
Also there is a lot of old files in Media library. 
![image](https://user-images.githubusercontent.com/4050715/84263323-bd42a080-ab38-11ea-932e-aef8fb32040f.png)

These files deleted, but I still see empty thumbnails.

**Comment by chetansatasiya** [comment] 2020-06-10 11:52
@AiratHalitov Can you please create support ticket and send all the info like admin detail of the site and SFTP so I can take look into this?

**Comment by chetansatasiya** [comment] 2020-06-11 04:08
@AiratHalitov 

For your development take a clone of this URL in your plugin directory: https://github.com/buddyboss/buddyboss-platform.git and switch to this `fix/1005` this branch and see this is working or not. I have feeling like I checked in ` LAMP server and both places working fine now maybe a some permission issue with you. 

Can you confirm one thing like Once you uoload a PDF then it is creating a preview file in `bb_documents` folder or not? It should look like this in Media https://prnt.sc/sxmlsb

**Comment by AiratHalitov** [comment] 2020-06-11 05:48
> maybe a some permission issue with you.

maybe you right

> Can you confirm one thing like Once you uoload a PDF then it is creating a preview file in bb_documents folder or not?

yes

![image](https://user-images.githubusercontent.com/4050715/84349500-e3b41a80-abd0-11ea-8c76-a3531caa7636.png)

> It should look like this in Media https://prnt.sc/sxmlsb

![image](https://user-images.githubusercontent.com/4050715/84349563-ffb7bc00-abd0-11ea-8910-5dea950bddfb.png)

**Closed** 2020-06-16 06:20 UTC
Labels: bug, priority: medium
