### ISSUE TITLE
BP Auto Group Join plugin is not working with the platform plugin.

### ISSUE THREAD

**Issue by archanabb** [buddyboss/buddyboss-platform#924] opened 2020-05-21 03:12 UTC
**Describe the bug**
BP Auto Group Join plugin is not working with the platform plugin.

**To Reproduce**
1. Install and Setup the BP Auto Group Join plugin
2. Check the groups
3. No user joins automatically (existing user/new user both)

**Expected behavior**
It should work without any issue just like it works with the BP plugin. 

**Support ticket links**
- https://secure.helpscout.net/conversation/1171037047/74392/

**Comment by chetansatasiya** [comment] 2020-05-21 04:22
@archanabb I am closing the issue because it's already in built in platform you don't need this plugin anymore.

**Comment by archanabb** [comment] 2020-05-24 06:36
I checked this thoroughly, we don't have this feature built-in in the platform plugin.

**Comment by jrbuddyboss** [comment] 2020-10-03 18:23
Related Ticket:
https://secure.helpscout.net/conversation/1296962337/101364/

**Comment by janakkaneriya007** [comment] 2020-10-05 05:59
@jrbuddyboss @ankitguptaindia 
Fixed the issue with the auto group joining and shared with internal team to review.

**Comment by janakkaneriya007** [comment] 2020-10-21 07:35
@sourabhmatolia 

The issue has been fixed with the BP Auto Group Join plugin and I had sent it for review to @mehulkaklotar  and he has approved it and @ankitguptaindia can confirm after he tests it that the issue is fixed.

**Comment by christinabbsupport** [comment] 2020-10-21 22:36
https://secure.helpscout.net/conversation/1315397689/104298?folderId=3701264

**Comment by ankitguptaindia** [comment] 2020-10-22 10:31
This is Live now with fixes. https://wordpress.org/plugins/bp-auto-group-join/


Closing this issue. 

@sourabhmatolia  @janakkaneriya007 @chetansatasiya

**Closed by ankitguptaindia** 2020-10-22 10:31 UTC
Labels: Type: Support, priority: high
