### ISSUE TITLE
Events Calendar Pro - recurring events generate multiple Activity records (annoying)

### ISSUE THREAD

**Issue by KaloyanNaumov** [buddyboss/buddyboss-platform#941] opened 2020-05-28 17:04 UTC
**Is your feature request related to a problem? Please describe.**
1. Events Calendar Pro - recurring events generate multiple Activity records. Flooding the Feed with the same post over and over again. This is achieved with a "Recurrence Rule" when scheduling.

2. BuddyPress Theme: Event posts in the Activity feed are missing time, date and venue indication. this is more for the theme , but we, as users don't have access to the report to submit in the theme requests. The implementation of event posts in the Event Calendar WIdgets is beautiful.

**Describe the solution you'd like**
Upon creating of recurring event (requires Events Calendar PRO), only one of the events will be displayed. Ideally, with indication of recurring rule, being displayed.

It would also look much better if we also see the event post styled more as an "event" entry, with the date & time, recurrence, venue. This is for the BB theme, though.

**Describe alternatives you've considered**
Since I want recurring events, I need to switch off the Events from the Feed ... Other option would be to manually delete activity posts, **_upon creation and every edit_**
We are using BuddyBoss for a Meditators community and want to have regular daily schedule of meditations and practices.

As per the date/time/venue display, I can work-around it by adjusting the event post text to have information. Not ideal, but somewhat acceptable.

**Support ticket links**
No communication with Support on this - no need to consume valuable support time for this.

**Comment by eisenwasser** [comment] 2020-05-29 17:55
@KaloyanNaumov Thanks, we will review

**Comment by janakkaneriya007** [comment] 2020-11-11 12:49
@KaloyanNaumov 

Can you please do the video of reproducing the issue? I am not able to reproduce on my end.

**Comment by marienel21** [comment] 2021-06-21 18:13
Hi @KaloyanNaumov ,

Thank you for your feature request.

We have imported this request into our product management system and will review it when planning new product features. You can see the features we're working on, as well as suggest new features, on our public roadmap: http://buddyboss.com/roadmap

I'll be closing this issue now in order to keep our GitHub issues focused on tasks that are ready for development.

Marienel
BuddyBoss Product Team

**Closed by marienel21** 2021-06-21 18:13 UTC
Labels: feature: customer
