### ISSUE TITLE
Move Photo functionality is not working properly. 

### ISSUE THREAD

**Issue by mohit-buddyboss** [buddyboss/buddyboss-platform#2401] opened 2021-05-13 13:03 UTC
**Describe the bug**
After moving one photo in A album if user tries to move second photo in same album then user is not able to do it because move restrictions are getting set for all photos after moving first photo.

Verified this on demo website and also on local server by creating fresh setup. 

**To Reproduce**
1. Create new user.
2. Upload new photos.
3. Create 2 albums > Primary and Secondary
4. Now move first photo in primary album. 
5. After that try to move second photo in primary album. 
6. User will not be able to move second photo in Primary album because it is got restricted after moving 1st photo.
7. Because 1st photo is in primary album user can't move that photo in same album. Same restrictions are working for other photos also which are not in Primary album.

**Expected behavior**
One photo move restrictions must not get apply to other photos. 

**Video**
https://www.loom.com/share/9a95b6d81b924fd8bec7c99a7857a561

**Support ticket links**
N/A reported internally by QA

**Comment by surajkrsingh** [comment] 2021-09-07 11:26
@mohit-buddyboss @dipskakadiya 
We tested this issue and were not able to replicate it on the BuddyBoss demo
Also tested on local dev site but can't reproduce.

**See this -** https://drive.google.com/file/d/11SbtMyWvV509FlTwcVQMEEBJacSDDc-P/view

**Comment by mikejyoung** [comment] 2021-09-23 14:58
Closing issue.

**Closed by mikejyoung** 2021-09-23 14:58 UTC
Labels: bug, bug: can't reproduce, priority: medium
