### ISSUE TITLE
Timeline is freezing after few pages of scroll

### ISSUE THREAD

**Issue by mehulkaklotar** [buddyboss/buddyboss-platform#2292] opened 2021-03-31 12:41 UTC
**Describe the bug**
Timeline is freezing after few pages of scroll. Infinite scroll is freezing the browser. It has some javascript code that runs on every page request and we need to look for those js codes that affects it.

**To Reproduce**
1. Go to News Feed
2. Scroll down and keep doing load more. (Make sure you have lots of feed content like Embeds,media, documents etc.)

**Expected behavior**
It should not freeze the browser and should run smoothly without any issues.

- There is one js code that looks for Embed links in activity content and removes it if activity has no content other than that link which is being embedded. So I guess that code is being executed on each ajax request of activity fetch on pagination and once we have like 100 or more than 500 activities on the page, it runs on them and freezes the browser.
- There may be other places where we could be doing this type of unnecessary execution. we need to find them.

**Comment by krunal-buddyboss** [comment] 2021-08-11 08:17
@sourabhmatolia @chetansatasiya @KartikSuthar 

I have checked this issue and try to reproduce it on local and on our demo site but I am not able to reproduce it.
I have loaded approx 20+ pages but it works fine for me, please see below video record from our demo site.
https://www.loom.com/share/ea981b6fa63a44ebb662ef3fd0b7fb1e

Please let me know if I can add can't produce label and close it.

Thanks.

**Closed** 2021-08-12 15:27 UTC
Labels: bug, bug: can't reproduce, priority: medium
