### ISSUE TITLE
Connection's posted picture not showing on my timeline

### ISSUE THREAD

**Issue by ld-rlph** [buddyboss/buddyboss-platform#1228] opened 2020-07-18 04:05 UTC
**Describe the bug**
Whenever my connection or followed profile posts an image with a caption, the post shows on my timeline but only the caption, the image is missing

**To Reproduce**
1. Post something with an image on your connection's account
2. Login on your account and go to your timeline, you will your connection's post but without the image uploaded

**Expected behavior**
It should have the image show as well as the caption on my timeline

**Screenshots**
![Capture](https://user-images.githubusercontent.com/5795862/87844347-dc2e1280-c8ee-11ea-8dbb-4054b3624ee4.JPG)
![Capture2](https://user-images.githubusercontent.com/5795862/87844349-ddf7d600-c8ee-11ea-94bf-ecb1b9310935.JPG)

**Support ticket links**
https://secure.helpscout.net/conversation/1227405727/83625

**Comment by buddy4kp** [comment] 2020-07-31 12:36
Hello @ld-rlph 

I have checked on demo site that I can not reproduce this issue. Please check below video of working this issue.

https://www.loom.com/share/b1a411d451714488aa198f6fda6ee6c5 

I am going to close this issue. Please let me know you are still facing any issue in it.
Thanks.

**Comment by bb-ralph** [comment] 2020-08-01 03:26
I tried it again and I can still replicate the issue.
I have made a screencast, here's the link: https://www.loom.com/share/05c0ed0b6f004091b56045984726d0ec

**Comment by bb-ralph** [comment] 2020-08-01 03:27
Please re-open this ticket.

**Comment by chetansatasiya** [comment] 2020-08-03 09:30
@bb-ralph 

Local Dev Branch: https://www.loom.com/share/df788121bbe34dea9716bbce98f43208

Demo Master Branch: https://www.loom.com/share/395e3d86e1f644a399ee3d7c33c2adc9


I am not able to reproduce this issue on demo site as well as local dev branch so may be issue is fixed in recent release.

@bb-ralph I am closing this issue at this moment and feel free to reopen if I am missing anything to reproduce the issue.

**Closed by chetansatasiya** 2020-08-03 09:30 UTC
Labels: bug, can't reproduce, priority: medium

**Comment by bb-ralph** [comment] 2020-08-04 05:16
Issue resolved.

Thank you!
