### ISSUE TITLE
Change of username does not affect memberpress

### ISSUE THREAD

**Issue by harshadmane** [buddyboss/buddyboss-platform#2272] opened 2021-03-25 03:03 UTC
**Describe the bug**
When we change the username in BuddyBoss it doesn't change the username in MemberPress.

MemberPress support says "The integration between MemberPress and BuddyBoss was built out by them (BuddyBoss), so it's difficult to say for certain what it should/shouldn't do as the code wasn't written by us. However, the Members page will only show the new username if the username was actually changed under the Wp-Admin -> Users page. If it wasn't changed there, then it'd just need to be updated and it should be reflected on the Members page."

**To Reproduce**
1. Go to BuddyBoss > Edit Profile
2. Change the username
3. Go to WordPress admin > MemberPress > Users
4. The username is still old username its not changed.

**Expected behavior**
The username should change in BuddyBoss

**Screenshots**
Video: https://vimeo.com/524263221/ae29056c20

**Support ticket links**
https://secure.helpscout.net/conversation/1455203338/130916?folderId=3709081

**Comment by mahedihasannoman** [comment] 2021-08-30 11:51
Hi @harshadmane & @marienel21 , As per video client is changing nickname(labeled as username) not username. Anyway username is not changeable in Wordpress by default: https://nimb.ws/tDgBf5 
So the issue is not valid and closing this ticket.

**Closed by mahedihasannoman** 2021-08-30 11:51 UTC
Labels: bug, integration: official
