### ISSUE TITLE
Warnings/Notice on fresh Install of Platform

### ISSUE THREAD

**Issue by ankitguptaindia** [buddyboss/buddyboss-platform#996] opened 2020-06-08 07:24 UTC
**Describe the bug**
Warnings/Notice on fresh Install of Platform. 

**To Reproduce**
1. Go to Plugins Page 
2. Activate Platform plugin
3. Enable Debug 
4. See error on Members Profile page

**Expected behavior**
Log should be clear.

**Screenshots**
https://prnt.sc/svqd40
https://www.loom.com/share/afe1e514cda745238c8c4b6fab115c19

**Support ticket links**
NA

**Comment by ankitguptaindia** [comment] 2020-06-08 07:29
@chetansatasiya @eisenwasser Please assign to respective dev

**Comment by krunal-buddyboss** [comment] 2021-07-23 11:23
@sourabhmatolia @chetansatasiya 
I have checked and not able to reproduce this issue so we can close it. Please let me know your feedback.

@sumitbuddyboss @mohit-buddyboss  If you get chance, please confirm that we can not reproduce this issue so that we can close it.

Thanks.

**Closed** 2021-08-03 15:38 UTC
Labels: bug, bug: can't reproduce, priority: medium
