### ISSUE TITLE
Forum page with group associated title tag issue

### ISSUE THREAD

**Issue by kent-carlo** [buddyboss/buddyboss-platform#2933] opened 2021-09-15 07:42 UTC
**Describe the bug**
When the forum page is associated with the group, there's an issue with the title tag.

**To Reproduce**
1. Create a forum and associate it with the group.
2. Check the forum page.
3. You'll see that title gets weird.

**Expected behavior**
The title should be normal as what it is when the forum has no group associated.

**Screenshots**
Forum with no group: https://prnt.sc/1rtkptv
Forum with group: https://prnt.sc/1rtkptv

**Environment**
Which site did you replicate this issue on? Demo site

**Support ticket links**
https://secure.helpscout.net/conversation/1621712112/162415?folderId=4222125

**Comment by nickchomey** [comment] 2021-09-15 07:46
This is in relation to my ticket. There are a variety of symptoms that appear to have been overlooked, so I'd just like to add some details here that I included at the start of the ticket, just so they don't get missed. 

When you create a topic in a standalone forum, the browser/page title shows as [Discussion Topic Title] - [Site Name].

However, when you create a topic in a Group-associated Forum, the page title excludes the Topic Title and displays as "Discussions" - [Group Name] - [Site Name].

However, if you make a topic whose title is only numbers - e.g. 1234 - it will display as "Discussions" - [Group Name] - "Page" [Topic Title] -[Site Name].

This is somewhat annoying. But what the real problem is is that when you paste a link to these discussion topics in the activity feed, the same title is used in the preview, which makes the link completely uninformative.

Moreover, the activity feed preview for standalone forum topics is completely broken. 

So, I see a few issues:

1. The bug should be fixed for Group Forum topics, so that it shows the Topic Title in the browser window as well as url previews in the activity feed.
2. The "Page" label should be removed from the Group Forum Topics so that it reads "Discussions" - [Group Name] - [Topic Title] -[Site Name]. 
3. The standalone Forum should probably match the formatting of the Group Forum, such as "Discussions" - [Forum Name] - [Topic Title] -[Site Name].
4. The preview for Standalone Forum topics should be fixed to not be completely broken, and instead match the (now fixed) format of the Group Forum topics.

**Comment by kent-carlo** [comment] 2021-09-15 07:48
Thanks @nickchomey

**Comment by TokumeiJG** [comment] 2021-11-05 01:05
I have the same issue and reported it in July 2021 (Ticket # 156317)

It is reproducible on the demo site.

Adding to @nickchomey's comment, this is annoying if pasted in the activity feed.  

**However**, the bigger issue is that this page title is what shows up on _other sites_ (ie sharing to Twitter, Facebook, etc). so if you share there to try to get people to your site, it is a completely undescriptive preview and if you share often, it is a series of undescriptive links! 

The **Biggest** issue is search results in Google.  We want our forums to be discoverable and bring in new users who search the web, click through to our site, and then want to become a member so they can join in the discussion.  But, as mentioned, _whatever the topic_ is it only shows up as "Discussions - [Group Name] - [Site Name]" in Google!  This REALLY hurts SEO and limits community growth.

**ie** if you have a site called _AppleTalk_ and a group called _iPhone Chat_. If there are the topics "Latest iOS", "Updating Apps" and "restoring a backup"

Instead of useful Google results showing:
"Latest iOS - iPhone Chat - AppleTalk"
"Updating Apps - iPhone Chat - AppleTalk"
"restoring a backup - iPhone Chat - AppleTalk"

They show up as:
"Discussions - iPhone Chat - AppleTalk"
"Discussions - iPhone Chat - AppleTalk"
"Discussions - iPhone Chat - AppleTalk"

**Comment by TokumeiJG** [comment] 2021-11-05 03:11
@eisenwasser How long would this take to fix/change?

**Comment by TokumeiJG** [comment] 2021-11-10 04:34
I have a solution and BuddyBoss is free to add it (based on [this post](https://buddydev.com/making-wordpress-seo-plugin-compatible-with-buddypress-part-2/) and various Stack Exchange posts!)

Changing the Meta Title:

```
add_filter(` 'pre_get_document_title', 'change_meta_title' );
function change_meta_title( $title ) {
	// only for a single group
	if ( bp_is_active( 'groups' ) && bp_is_group() ) {
			$post_id = false;
			//by default, use group title
			$group = groups_get_current_group();
			$newTitle = $group->name;
			
			//are we looking for forum?
			if ( bp_is_current_action( 'forum' ) && function_exists( 'bbpress' ) ) {
	
				$forum_ids = bbp_get_group_forum_ids();
	
				if ( $forum_ids ) {
					$post_id = array_pop( $forum_ids );
				}
	
				//check if we are at single topic
				if ( bp_is_action_variable( 'topic', 0 ) && bp_action_variable( 1 ) ) {
					
					//get the topic as post
					$topics = get_posts( array( 'name'      => bp_action_variable( 1 ),
												'post_type' => bbp_get_topic_post_type(),
												'per_page'  => 1
					) );
					
					if ( ! empty( $topics ) ) {
						$post_id = $topics[0]->ID;
						$newTitle =  bbp_get_topic_title($post_id) . " - " . $group->name . " - [[Your Site Name]]";
						//return the new meta title
						return $newTitle; 
					}
				}
			}

	
		}

    //return without changing the title if not a topic
    return;
}
```

Changing the Meta Description to the topic excerpt:

```
add_action( 'wp_head', 'change_meta_description',2);
function change_meta_description() {
	if ( bp_is_active( 'groups' ) && bp_is_group() ) {//for single group

		$post_id = false;
		//by default, use group description
		$group = groups_get_current_group();
		$newDesc = $group->description;

		if ( bp_is_current_action( 'forum' ) && function_exists( 'bbpress' ) ) {

			$forum_ids = bbp_get_group_forum_ids();

			if ( $forum_ids ) {
				$post_id = array_pop( $forum_ids );
			}

			//check if we are at single topic
			if ( bp_is_action_variable( 'topic', 0 ) && bp_action_variable( 1 ) ) {

				//get the topic as post
				$topics = get_posts( array( 'name'      => bp_action_variable( 1 ),
											'post_type' => bbp_get_topic_post_type(),
											'per_page'  => 1
				) );
				//get the id
				if ( ! empty( $topics ) ) {
					$post_id = $topics[0]->ID;
				}
			}
		} 
		//if the post id is given
		if ( $post_id ) {
			global $post;
			$save_post = $post;
			$post = get_post($post_id);
			setup_postdata($post);
			$output = get_the_excerpt($post);
			wp_reset_postdata();
			$post = $save_post;
			//update description
			?><meta name="description" content="<?php echo $output ?>"/>
			<?php return; 		
		}
	}
}
```

**Comment by nickchomey** [comment] 2021-11-10 13:48
@TokumeiJG nice work! Which file is this in? Or is it just a snippet that you put in functions.php/or a snippets plugin?

**Comment by TokumeiJG** [comment] 2021-11-10 14:00
@nickchomey Just plop those in the child theme's functions.php file and you should be good to go.
They are sloppy bits of code stitched together by a non-programmer and very likely to break, so BuddyBoss still needs an official fix, but it should work for now...

**Comment by nickchomey** [comment] 2021-11-10 14:10
Thanks. Looking at this (specifically the "pre_get_document_title" and "wp_head" hooks) gives me a headstart for coming up with a real fix. Not sure when I'll have time, but probably sooner than BB...

**Comment by TokumeiJG** [comment] 2021-11-11 00:25
Awesome, keep us posted.

**Comment by nickchomey** [comment] 2021-11-27 02:46
One other thought - if the discussion is in a subforum, the title should probably include both the parent and subforum name

**Comment by milanhirapra** [comment] 2021-12-02 07:28
We have multi-level sub forums then the title look like (Parent Forum Title + Sub Forum Title + Sub Forum Title + Sub Forum Title + Discussion Title) and it will be too long. So, we have keep same for sub forum discussion.

CC: @sourabhmatolia

**Comment by nickchomey** [comment] 2021-12-02 14:43
Perhaps the best solution for this would be providing a setting, like with WordPress permalinks, to allow users to set their own structure with wildcards  %forum% - %subforum% - %title% - %website name%

**Comment by sourabhmatolia** [comment] 2021-12-08 12:03
Hello @nickchomey 

That's a good suggestion.
With this task specifically, we are trying to fix inconsistency with the title for Discussions.

Please add your suggestion as a feature request here:
https://www.buddyboss.com/roadmap/

We will take it from there. Thank you.

**Comment by nickchomey** [comment] 2021-12-11 15:55
I now see that you've created a PR for this issue and it looks like it will produce a page title for group forum topics as follows:

`[Topic Title] - [Group Name] - [Site Name]`

However, as described in great detail in my [initial comment](https://github.com/buddyboss/buddyboss-platform/issues/2933#issuecomment-919781322) in this issue, I think it should include "Discussions" because there are other tabs and activities within a Group. Moreover, this modification should also apply to standalone forums as well - both for consistency and clarity - which currently only display as `[Topic Title] - [Site Name]`

Overall, I think the following is the best format for both types of forums, moving from most specific to most general:

`[Topic Title] - [Discussions] - [Group/Standalone Forum Name] - [Site Name]`

with the value for [Discussions] taking its value from `bp_is_action_variable( get_option( '_bbp_topic_slug', 'discussion' )`

**Closed** 2021-12-22 11:28 UTC
Labels: bug, bug: validated
