### ISSUE TITLE
LearnDash LMS - bbPress plugin through the admin notice.

### ISSUE THREAD

**Issue by meetmakadiya** [buddyboss/buddyboss-platform#2973] opened 2021-09-24 15:39 UTC
**Describe the bug**
when we use the **BuddyBoss Platform** and **LearnDash LMS - bbPress Integration** that time through the admin notices for the required the bbpress, that should not show on the site.
We provide the support for all LearnDash Add-ons: http://i.imgur.com/Qhm7Qpp.png

**To Reproduce**
1. active the BuddyBoss Platform plugin 
2. active the LearnDash LMS - bbPress Integration plugin.
3. See error. 

**Expected behavior**
Admin notices should not show on the site.

**Screenshots**
http://i.imgur.com/i5W5jEU.png

**Environment**
Customer environment.

**Support ticket links**
https://secure.helpscout.net/conversation/1620537445/162187/

**Comment by bb-yudhisthir** [comment] 2021-10-06 11:16
Closing this issue as the issue is with the third party addon plugin from learndash, which is checking the bbpress plugin file and bbpress installed or not

https://screencast-o-matic.com/i/cr61XlVX6Db

**Closed by bb-yudhisthir** 2021-10-06 11:16 UTC
Labels: bug, bug: needs validating
