### ISSUE TITLE
Undefined variable 'online_count' notice in 'Who's online' widget. 

### ISSUE THREAD

**Issue by Anve-sri** [buddyboss/buddyboss-platform#730] opened 2020-04-10 13:38 UTC
**Describe the bug**
 Notice: Undefined variable: online_count in C:\Users\Anveshika\Local Sites\anveall\app\public\wp-content\plugins\buddyboss-platform\bp-members\classes\class-bp-core-whos-online-widget.php on line 

in 'Who's online' widget. 

**To Reproduce**
1. Go to 'Appearance > Widgets'
2. Assign 'Who's Online' widget to 'Activity' page.
3. See error

**Screenshots**
https://prnt.sc/rws52f

**Support ticket links**
https://secure.helpscout.net/conversation/1130579348/67421?folderId=3701249

**Comment by janakkaneriya007** [comment] 2020-04-10 15:56
Duplicate of: https://github.com/buddyboss/buddyboss-platform/issues/725

**Closed by janakkaneriya007** 2020-04-10 15:56 UTC
Labels: bug, priority: medium
