### ISSUE TITLE
Comment is not working in the group feed

### ISSUE THREAD

**Issue by milanhirapra** [buddyboss/buddyboss-platform#2616] opened 2021-07-14 11:51 UTC
**Describe the bug**
If **Edit Activity** is enabled then the comment is working fine for all activities but if we disable then the comment is not working only in group activities.

**To Reproduce**
1. Go to BuddyBoss > Settings > Activity
2. Enable **Edit Activity** option
3. Go to the Activity feed and click on the comment link it's showing comment form
4. But, if disable **Edit Activity** option
5. Go to the Activity feed and click on the comment link of group activities it's not showing comment form

**Expected behavior**
Comment form should be displayed if click on comment.

**Screenshots**
https://www.loom.com/share/f6ad27b59e274ca49367c92a1c34dd44

**Environment**
https://demos.buddyboss.com/online-communities/

**Support ticket links**
https://secure.helpscout.net/conversation/1563456544/151548/

**Comment by chetansatasiya** [comment] 2021-07-14 11:54
Closing this as it's a duplicate of https://github.com/buddyboss/buddyboss-platform/issues/2596

**Closed by chetansatasiya** 2021-07-14 11:54 UTC
Labels: bug, bug: needs validating
