### ISSUE TITLE
(Component Report) Feed takes 30 seconds to load

### ISSUE THREAD

**Issue by Felipemauah** [buddyboss/buddyboss-platform#2030] opened 2021-01-11 17:26 UTC
Hi! After enabling the Component report, the Feed went from 2 seconds to more than 30 to load, both the main feed and the profile and group feeds.
I disabled the component to check if it was it that was causing this delay and when disabling it, the loading of the feed returned to normal.

This delay started to happen not only in the complete loading of the feed, but also, in the automatic loading that happens when we reach the end of the Feed.

I disabled some plugins to make sure it was not conflict and not to get any improvement. The component works very well, however, there is communication on my website about this problem.

This load to which I am referring, is the one in which a message appears requested for the user to wait because the feed is being loaded, it is at that moment that it remains for more than 30 seconds.

Thanks for the support and excellent product.

**Comment by grahamhoffman** [comment] 2021-08-17 11:31
Thank you for adding this issue, however as per the [notes](https://github.com/buddyboss/buddyboss-platform#support), this repository is not suitable for support issues. I’m going to close this ticket but if the problem is still outstanding please submit a support request at your [BuddyBoss.com](http://buddyboss.com/) account.

**Closed by grahamhoffman** 2021-08-17 11:31 UTC
Labels: bug, priority: medium
