### ISSUE TITLE
Group Message reply show notification as a new Private private message to everyone on that group member

### ISSUE THREAD

**Issue by jakir-git** [buddyboss/buddyboss-platform#2046] opened 2021-01-15 18:05 UTC
**Describe the bug**
When someone replies on a Group Message then it's show notification as a new Private private message to everyone on that group member

**To Reproduce**
Reply on a group message and check as other member notification.

**Screenshots**
https://prnt.sc/wpu7dl

**Support ticket links**
https://secure.helpscout.net/conversation/1390505111/118809?folderId=3955985#modal

**Comment by krunal-buddyboss** [comment] 2021-01-19 12:02
Hello @jakir-git 
I have checked with team and found that it is not a bug, it is default behavior of plugin. if user reply from message page it will be consider as private message and if user reply from the group "Send message" tab then only it will be consider as group message.
I am going to close this issue, let me know if sill it is no clear.
Thanks 
+ @sourabhmatolia

**Closed by krunal-buddyboss** 2021-01-19 12:02 UTC
Labels: bug, priority: high
