### ISSUE TITLE
SQL errors related to BuddyBoss groups when using Memberium

### ISSUE THREAD

**Issue by ayron-paul** [buddyboss/buddyboss-platform#395] opened 2019-12-21 21:16 UTC
**SQL Error from client**
`WordPress database error Table 'pygtrain_main_site.g' doesn't exist for query SELECT DISTINCT g.id FROM g ORDER BY g.date_created DESC LIMIT 0, 20 made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plugins_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, memberium_frontend->doAutologin, do_action('wp_login'), WP_Hook->do_action, WP_Hook->apply_filters, memberium_frontend->wpLogin, memberium_frontend->populateSession, memberium_core->generateSession, apply_filters('memberium_session_filter'), WP_Hook->apply_filters, BP_Groups_for_MemberiumAutoJoin, groups_get_groups, BP_Groups_Group::get`

**Issue**
When Memberium tries to get the group list using BP_Groups_Group::get it returns an error

**Findings**
It seems that the class **BP_Groups_Group** from BuddyBoss Platform is using some SQL queries that were trying to call a non-existing table. For example on /wp-plugins/buddyboss-platform/bp-groups/**_class-bp-groups-group.php_** please see **_line 1120,_** a **_table named "g"_** is being used or called. Also, there might be some files under /bp-groups/ that have this kind of issue. 

**Expected behavior**
BP_Groups_Group::get should be able to return the list of groups without error

**Alternative method to replicate (without using Memberium)**
Try to use the following code
`$groups = BP_Groups_Group::get(array(
              'type'=>'alphabetical',
              'per_page'=>5
              ));
          print_r($groups);`

You will get this kind of error
![tablename-g](https://user-images.githubusercontent.com/58522498/71313852-e6338400-2479-11ea-9b1f-4d258d6c2a07.png)

**Support ticket links**
https://secure.helpscout.net/conversation/1111983635/6180/

**Comment by jaydeeprami** [comment] 2020-04-30 07:58
@ayron-paul ,

I am not able to reproduce this issue. I have enabled `WP_DEBUG` as well.

I have tried with and without the Memberium plugin.

I have tried with run below code as well:
```
$groups = BP_Groups_Group::get(array( 'type'=>'alphabetical', 'per_page'=>5 ));
```

FYI: I have installed below Plugins: https://prnt.sc/s8gji1

Please let me know if anything else needs to do to reproduce.

Or Please provide steps to reproduce.

Thanks

**Comment by ayron-paul** [comment] 2020-06-26 19:33
Hi @jaydeeprami, I am not able to reproduce the error anymore with the latest version of Memberium and BuddyBoss. We can close this then. Thank you very much.

**Comment by chetansatasiya** [comment] 2020-06-26 21:14
@ayron-paul Thanks for confirming. I am closing this ticket at this moment.

**Closed by chetansatasiya** 2020-06-26 21:14 UTC
Labels: bug, can't reproduce, component: groups, priority: medium
