### ISSUE TITLE
Member Page > Pagination concern with back button

### ISSUE THREAD

**Issue by rmmehta** [buddyboss/buddyboss-platform#2976] opened 2021-09-27 07:03 UTC
**Describe the bug**
On the Member page if say we have 5 pages and if we click on member profile and then press back button then it goes to 1st page of member page not on the last page.

**To Reproduce**
1. Go to 'member page'
2. Click on 'second page'
3. click on any user profile and press back button 

**Expected behavior**
If we are on 5th page and click on any user and press back button it take us on the last pagination page on on the first page on member page.

**Screenshots**
https://www.loom.com/share/97afb2c3989a4642a50f55f13abe9bf0

**Environment**
On client side and on our demo site as well

**Support ticket links**
https://secure.helpscout.net/conversation/1629678393/163801/

**Comment by bb-yudhisthir** [comment] 2021-11-12 08:38
@rmmehta As discussed with you and confirmed from @dipskakadiya, already its the not a bug and default ajax pagination behavior.
With the default ajax pagination we have implemented its the the default behavior as by default the state is not maintained so its not an issue as its made how it is so closing this

You can ask the customer to create a feature request

**Closed by bb-yudhisthir** 2021-11-12 08:38 UTC
